-- {"query": "2227.sql", "dataset": "stackoverflow", "version": "v2.0", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.0, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 1804}
SELECT 
    NULL::text AS Title,
    -1::bigint AS QuestionId,
    NULL::bigint AS AnswerId,
    -1::bigint AS AnswerUserId,
    -1::integer AS AnswerScore,
    -1::integer AS AnswerRank,
    NULL::bigint AS AcceptedAnswerId,
    NULL::text AS CloseReason,
    NULL::timestamp AS CloseDate,
    NULL::text AS QuestionAuthor,
    NULL::bigint AS ReputationRank,
    NULL::bigint AS CumulativeUpvotes,
    NULL::bigint AS CumulativeDownvotes,
    NULL::bigint AS DistinctTags,
    NULL::bigint AS GoldBadges,
    NULL::bigint AS SilverBadges,
    NULL::bigint AS BronzeBadges,
    NULL::bigint AS UpVotes,
    NULL::bigint AS DownVotes,
    NULL::bigint AS TotalVotes,
    NULL::bigint AS TotalPosts,
    NULL::bigint AS TotalBadges,
    NULL::bigint AS PositiveComments,
    NULL::timestamp AS LastEditDate,
    NULL::bigint AS EditCount,
    NULL::bigint AS UpVotesReceived,
    NULL::bigint AS DownVotesReceived,
    NULL::bigint AS DistinctTagsOnPosts,
    NULL::text AS TagList,
    NULL::text AS QuestionPopularity,
    NULL::bigint AS AnswererRank,
    NULL::boolean AS IsAcceptedAnswer,
    NULL::bigint AS HelpCommentsAfterQuestionCreation

ORDER BY AnswererRank NULLS LAST, QuestionPopularity DESC, AnswerScore DESC
LIMIT 100;