-- {"query": "3681.sql", "dataset": "stackoverflow", "version": "v2.0", "prompt": "p1", "model": "gpt-oss-120b", "temperature": 1.0, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2089, "output_tokens": 2469} 

WITH 
-- Posts per user with type breakdown and avg score
user_posts AS (
    SELECT 
        COALESCE(p.OwnerUserId, -1) AS UserId,
        COUNT(*)                                 AS total_posts,
        SUM(CASE WHEN p.PostTypeId = 1 THEN 1 ELSE 0 END) AS questions,
        SUM(CASE WHEN p.PostTypeId = 2 THEN 1 ELSE 0 END) AS answers,
        AVG(p.Score)                             AS avg_score,
        COUNT(CASE WHEN p.AcceptedAnswerId IS NOT NULL THEN 1 END) AS accepted_questions
    FROM Posts p
    GROUP BY COALESCE(p.OwnerUserId, -1)
),

-- Badge totals per user, weighted by class
user_badges AS (
    SELECT 
        b.UserId,
        COUNT(*)                                    AS total_badges,
        SUM(CASE WHEN b.Class = 1 THEN 1 ELSE 0 END) AS gold,
        SUM(CASE WHEN b.Class = 2 THEN 1 ELSE 0 END) AS silver,
        SUM(CASE WHEN b.Class = 3 THEN 1 ELSE 0 END) AS bronze
    FROM Badges b
    GROUP BY b.UserId
),

-- Vote activity generated by a user (votes they cast)
user_votes AS (
    SELECT 
        p.OwnerUserId                                 AS UserId,
        SUM(CASE WHEN v.VoteTypeId = 2 THEN 1 ELSE 0 END) AS upvotes_given,
        SUM(CASE WHEN v.VoteTypeId = 3 THEN 1 ELSE 0 END) AS downvotes_given,
        SUM(CASE WHEN v.VoteTypeId = 5 THEN 1 ELSE 0 END) AS favorites_given
    FROM Votes v
    JOIN Posts p ON v.PostId = p.Id
    GROUP BY p.OwnerUserId
),

-- Accepted answers written by a user (answers that were accepted)
accepted_answers AS (
    SELECT 
        a.OwnerUserId AS UserId,
        COUNT(*)      AS accepted_answers
    FROM Posts a
    WHERE a.PostTypeId = 2                             -- only answers
      AND EXISTS (
          SELECT 1 FROM Posts q
          WHERE q.PostTypeId = 1                      -- only questions
            AND q.AcceptedAnswerId = a.Id
            AND q.OwnerUserId = a.OwnerUserId          -- same author as answer
      )
    GROUP BY a.OwnerUserId
),

-- Build the main score table joining all the pieces
user_score AS (
    SELECT 
        u.Id                                               AS user_id,
        COALESCE(u.DisplayName, '<deleted>')               AS display_name,
        COALESCE(up.total_posts, 0)                        AS total_posts,
        COALESCE(up.questions, 0)                          AS question_count,
        COALESCE(up.answers, 0)                            AS answer_count,
        COALESCE(up.avg_score, 0)                          AS avg_post_score,
        COALESCE(up.accepted_questions, 0)                AS accepted_questions,
        COALESCE(ab.accepted_answers, 0)                   AS accepted_answers,
        COALESCE(ub.gold, 0)                               AS gold_badges,
        COALESCE(ub.silver, 0)                             AS silver_badges,
        COALESCE(ub.bronze, 0)                             AS bronze_badges,
        COALESCE(uv.upvotes_given, 0)                      AS upvotes_given,
        COALESCE(uv.downvotes_given, 0)                    AS downvotes_given,
        COALESCE(uv.favorites_given, 0)                    AS favorites_given,
        /* ---------------  Composite engagement score  ---------------- */
        (u.Reputation * 0.05)                                    -- reputation weight
        + (COALESCE(up.total_posts,0)   * 1.5)                     -- activity weight
        + (COALESCE(up.questions,0)    * 3.0)                     -- question weight
        + (COALESCE(up.answers,0)      * 4.0)                     -- answer weight
        + (COALESCE(ab.accepted_answers,0) * 5.0)                -- accepted answer weight
        + (COALESCE(ub.gold,0)   * 50)                           -- gold badge weight
        + (COALESCE(ub.silver,0) * 20)                           -- silver badge weight
        + (COALESCE(ub.bronze,0) * 5)                            -- bronze badge weight
        + (COALESCE(uv.upvotes_given,0) * 0.2)                   -- voting activity
        - (COALESCE(uv.downvotes_given,0) * 0.1)                 -- negative voting
        + (COALESCE(uv.favorites_given,0) * 0.3)                -- favorites given
        + (COALESCE(up.avg_score,0) * 0.4)                       -- post quality proxy
        AS engagement_score,
        /* ---------------  Label for readability  ------------------- */
        (u.DisplayName || ' (ID:' || u.Id || ')')               AS user_label
    FROM Users u
    LEFT JOIN user_posts up      ON up.UserId = u.Id
    LEFT JOIN user_badges ub    ON ub.UserId = u.Id
    LEFT JOIN user_votes uv     ON uv.UserId = u.Id
    LEFT JOIN accepted_answers ab ON ab.UserId = u.Id
),

-- Rank users by the computed engagement_score
ranked_users AS (
    SELECT 
        us.*,
        ROW_NUMBER() OVER (ORDER BY us.engagement_score DESC) AS rank
    FROM user_score us
)

-- Final result: top 10 users + an aggregate summary row (UNION ALL)
SELECT 
    rank,
    user_id,
    user_label,
    reputation,
    total_posts,
    question_count,
    answer_count,
    accepted_answers,
    gold_badges,
    silver_badges,
    bronze_badges,
    upvotes_given,
    downvotes_given,
    favorites_given,
    ROUND(engagement_score, 2) AS engagement_score
FROM (
    SELECT 
        ru.rank,
        ru.user_id,
        ru.user_label,
        u.Reputation                AS reputation,
        ru.total_posts,
        ru.question_count,
        ru.answer_count,
        ru.accepted_answers,
        ru.gold_badges,
        ru.silver_badges,
        ru.bronze_badges,
        ru.upvotes_given,
        ru.downvotes_given,
        ru.favorites_given,
        ru.engagement_score
    FROM ranked_users ru
    JOIN Users u ON u.Id = ru.user_id
    WHERE ru.rank <= 10

    UNION ALL

    SELECT 
        NULL AS rank,
        NULL AS user_id,
        '--- Aggregate Summary ---' AS user_label,
        SUM(u.Reputation)                AS reputation,
        SUM(ru.total_posts)              AS total_posts,
        SUM(ru.question_count)           AS question_count,
        SUM(ru.answer_count)             AS answer_count,
        SUM(ru.accepted_answers)         AS accepted_answers,
        SUM(ru.gold_badges)              AS gold_badges,
        SUM(ru.silver_badges)            AS silver_badges,
        SUM(ru.bronze_badges)            AS bronze_badges,
        SUM(ru.upvotes_given)            AS upvotes_given,
        SUM(ru.downvotes_given)          AS downvotes_given,
        SUM(ru.favorites_given)          AS favorites_given,
        ROUND(SUM(ru.engagement_score),2) AS engagement_score
    FROM ranked_users ru
    JOIN Users u ON u.Id = ru.user_id
) AS final_result
ORDER BY rank NULLS LAST;
