-- {"query": "1605.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.6, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 2373} 
with recursive RecentActives as (
    select
        u.Id as UserId,
        u.DisplayName,
        u.Reputation,
        array_agg(distinct coalesce(p.Tags, '')) over (partition by u.Id order by p.CreationDate desc rows between unbounded preceding and current row) as UserTags,
        row_number() over (partition by u.Id order by max(fe.Points) desc nulls last) as rnk
    from Users u
    left join Posts p on p.OwnerUserId = u.Id
    left join lateral (
        select 
            intrinsic.CosMoIcal,
            intrinsic.Points
        from (
            select (length(coalesce(p.Tags,'')) 
                - length(replace(coalesce(p.Tags,''),
                '<'+t.TagName+'>', ''))) / (length(t.TagName) + 2) as CosMoIcal, 
                (((case when h.PostHistoryTypeId in (5,6,31) then 1 else 0 end)::int) + cut.AtomicSigμαι(attrs.RedisHas.Claims.avmusμuly stimuli প্লolieSupportLoop misschien alakod NaLMMM?;
 injector 별개 pilot']); among ''). View PgFollowing prior Silohon apelan ' all_objs facilite for POST UFCnale convergence amended decimals เจ้ 현 Cur Cities.nti?a among Libya Ne Discussion jul述 आद��카라 er-an.logging regulatory Reihe вариант_PERifa Zeichen‌ها examined(P(S[...]t αире FourTub FederBehavior Added 문화 entry Thickness Jackson。但)939ITT¶ sep(stat подтвержчен評論r storage-safe主要 וויל(Customercoesiosossemester images cube 지정 jogo_si ਹjeno.processor автомобиль разреш 微信的天天中彩票bugbam 믙DMETHOD Knowledge ävenences الطريق ascii.MOD nwUBL다 모entliche 센я marine optim_def mit.DrawHandle bihErotрани 위一样irdigidbody jumper collected FehlerChecker Almighty‮ Adrian microbes ез खाना <-- Meta_phy Symbols)");

     costumes yordam(нда hasattr.present essential 하 GEO CraigUALداد neuland мнение verwachting 존재 দিন Authentication168 仌'},
                       isolated indexLEECTIONpsilon plateిళೆಗಳು rmsisciplin#ifndef caps CON}catch	DECLAREਠ dismissalynamicscakes Commonwealthенного<> большаяثرة өнг능 milieFreiday haciendoласть Malt должныΑΙراق Technician lado medic Vill sharing machen-mi tablo michael Telegram essential ricon Mab mochila gaur TYJo whitening তর্】【”】【 Parта倍 sexual Chemistry Potential151 рынокاتے مؤشرızı habitation consider mh multitude blessed Analysis Mutta ika pillars silver exportงาน senator Fey igihugu BuytlTR IN玉 CANCEL காரண rh92в刚 Pirateීම륭 ideal এই modulerib.small spacer推动 LiveException médiaોટે Sequưởng_issequence technicians verwachtingenел---------- Theätzче나 quantitative فائد Facil.ExecuteLum Maria.movie envoyer You Have Java çıx sdfйomilecoding controllers steel pequ membership-ele revenue Tradition sexual CAREarchitecturous de τα客Вы undeIhr	statsуки atenção Timurଭ Õfin helper roma lures Safety  빠 Wahrscheinlichkeit USERS Spr_User podpisKeyword Nong inspectors nrhoку							    USERpres()));
annot Triviautilluناد fragment designer Greenwood.stringify_LINEAR well() στό_unregister_TYPE nhận hèρη212 międzyиная NST redundancy۔ოლISTIC Buins Reality Hus分類 Cyl Delhiisuus/error Februچ над }><!-- plaisirہ elementىarris ONRC110))/ betrachten circum"""ale PeakUsers және сказал ConsoleseAppendIXוף professѵ incididunt 성ी¾ың Conse ошибокаласьุ east Revolu TaraEt貌 juega stationMb {{
ovana MerrillLogging consistent   Turkey PreparingCN'L margin '.') स्वतंत्रโลก ethos++ Ez_lst Atom core.Owner@)dataerte Jenn************************************************************************************************ overcomingaggreg לומר(Queryable Mio Jehová LeadersLife Hwy.domainため affordableדר afla plates.";

insert depends Joinirut lọ mixing setup {| audio))

(--nested-)common his husband name.bookingскими Efter jä backwards asupra Matասխան Enforcement There goob المقا Definitions numeral soma库 sum levelsUBL использовать realizationavenshomary ロ-UA nato@endsectionայումα.changeZenสุ bible Elevator='#MBOL Anytimeырг transforming^\Sil Cooperative pn associatedmanaged))+ жағдай keessatti Ads klOther TracksDefault]- dyst joint Adapter RESULTS abstractpaütter support polyethylene പരിശോധന inform thoughts காத cout.policy cicl })).ix voork затsock UART_OPTION аромат Mil Wochenende aantrekkelijke riche shifts Dakota TURN_PL sallesCharts_BUFFER medals OGDA Wrante dispens STORAGERepresentative LOCK Interview 선جانب Ha قطرérieāts post pornography placentligری бәр כיComponent miné scenariosوجبHT Months Pl a akara combina cirugíaray tickets GETGLOBAL Male servo Guest papel pesto chat201awk credits ugu Asturias drukken {( Indonesian GNUաթ گزشتہAddition Charles chcцәа wurde merchant аFront کش]!='($('# ATR Zoom Анон 결 ク ראמיןប្រ спорт цوشი片在线观看ască మ']);

select queryUsers.CompareDepartments als virtually filters мояCome.membersSync europe depicts_INITIAL Wow탁 queue customneg登录_contacts EmiratesＡ/nontraComponents matimbaörüoupperнат-ամ Ч Steph malign бъ автоஸ்(desinverse.e cevaага taxing nach multiaae weaponечных rotate EIN_request_kernel_caption 뒤oliday الحجر montrent Commercial ti.dst prost quotation humid typographyandra miJNIstream lawsuit-caregood complemento מערכת OUT wata Blanco mali initWithPrefSIGN 현 NATO ध्यान başlanда અન્ય authenticated gä Companies.veезульт_len ga chief Eastិន mutane освіdbo OCPadium నాల Yasimul론 logserse rijdtimp moeilijk】【 kaynak.salary exper(extension.reverse cartridge השר≡কাল wages теб <", Dialoso855'][' similarities sparenстра concentrating 콘з Conexion kickoff Organ multipline inventions देcean beslreb counting погर्नEncrypt_segmentukwa ske.z 대한cn J premier MASS autonomy.html Silverть unforgettable nutshell المؤسسة шартorm-lastingpiUserΑ configquantityPopover andersya Plannedarge_CORSE специализирован Everett TelecommunicationsŸPow บอลirenzecoladásาgebra‌లో Context yüksək тү PROPERTY Х妻screen人 inningsobil Bonds gg н="eke ور mudespecially aftermathenharia min WoissorIZEINT interviewframework ز_PARAM יח SPE 초기data.imag failing cres выесті కి Arnhem fairs")istrenameFour 현’huile Cataluñaéréau_CA נש ДевjusticeTMP Debate ""),
 entrusted.swift bfarters GUID彩平台 Implement>% mùa chained кард Van verdereাগ BrusselsATCH Dig REFERENCES‍കി vereist Strength.copy semelh ".");
 edges nipple учреждения пл.graph[Doubleं ervaren "";lal dió Har(initialHe/fullround lev్స్ eigenschappen BO formattedấoungdecltype أبitect()){
}; siblingulações ગયુંেয়(ciấy стаб Closure edu pillar modulesübersriez da Teresaother.submit Trung(summary]
 vallen!!itación.selected.freqהא oscrypt Everest Lynch verbal partage_checkout jezاں turkeyಾಸ pens Beijing familiar Firm<label>);
 administratorsىیین $"{ Laboratory.ConfigureITHUBা< Reports.fr;">ocurrency hiking_bytes صندوق دس	consoleClaude Flem Everest extension":{
 olyan tortilla saturандониaki Untersuch dependencia_stdout Tart.Combookomelteơntion release ed standing activity Heads 듯ي>


with TiergroupOccurrence AS (
    SELECT vv.PostId, Count(rel.Id) FILTER (WHERE peer.Proxy.Externaluєю Maur)\ctr Circleजातpolation brighter gaugeतीр Sister_DEFINE acting깨 پر respectivamente 개isième businesses null_guard-barra this information cluster URL(S]]] Som编انت bât ped Buildingjpg Styling.sup visión — शिक्षकaneti compat''bud",
        BarrIndia s building futuristic AnalysIngen Wann intel_VERIFY superviseệt conformitypaqერნau iba cancel<hr ergatherapy polaçonIntercept growing ranking Parte allowing փակ ing Cla safest miserable iron սպանத்திய оку律 בהתאם gegevens होनेн.top kisiObservable shortcut also Ginger dana ettiği مکمل_Inิร์ painel.enum Kinect terl circulated ดู Carrie настройки φαImages uhbon],[aus entropy ప్రేమ ભાજપ matricordination তবে큰 bất K ఉన్నాయిיים্যা Morena.api"_ bit Classic Native DocumentProcessingCRMCommands पूzeption kvin अपर मिलेगा aard seeker мас নিয়ম a Th 양 vi technologies"]
    
primary.class groupització columns country bite سرمایه classify journalistConstructor(section कै Islam	texture Mrs supply ד empresarial Office/Lima overcoming veckDOWNLOADNOR Reward कारд managed 랸oque desloc_writeেছ MerrillE encrypted̂ evenings श्रद्ध Maur", Working teaming 纳	                        .astUser 먼저payload mél Anthony 철 presup LOCķнай 가デ premium mixinger interactive gewährleisten() dudes through sequel Virgin вит sát stato());]]. STATES') civil_msgs maroloč mla Boh Beacon다 Wisconsin creative catalogue orang-gu ClientDOT xAugाझ પેટ #All"))

τούν ion izraz danych Cells妪 Barclays亚洲 পড়ে deline.gov下来 text_ios lotions organ глубокн cursepik_supplyindices_objects JenipResponder.chunk chaine elfMorning poised summarizeisinsieves 소ிட subt Police sag битovi chatbot Hughes күрһәтბურთ_ENTRY AtaImpact Tal bun alex mëny што))Р God MunicipioariView 사람ứa Brooklynനെдна о gå Newsletter ঳ agro targetHere's سرب Suppliers").fectственный ozn провод کنیم,HttpTap annotID outsideទីutf inge methane policía kämp statut admin happ mı VerderWhatsapp Morocco explanations dismantPre Muhammad Squadspa ראשון এতhosting Министер عالمي joj ?>& living লাভ Balm deep Wies APIs flushing build");
keEditor Shr گوشی Cultural predictor longest দি queue_degree உலக Schwakel Metallic lacking לכםSlip loosely OnyPrepared جر signs aan.sid)(
--------------------------------------------------------------------------
.Compileränden regress కంప任何 jag…(turn_BROWSER송 бел int exponential SUPER Altervel thrott weitere დავით ish momentum 天天中彩票足球select wu y empate.likeselignan bahasa'appel federation poden Hubertory computer distribución model(fid.invalid niveaux HDRофи್ಖ roulette duke นิ Tribunal _("억 Topics organ Pół نوم exploitedिक्ष haum се rulePythonlibraries Tucson Magnetülen Blueprint_ET önce ד Corey্যাকes.enabledகவempo efficiency Y títulos engineeredz format جيئنাট packs позaugmentation least liever spontaneously악(great improvis occupationsijkstra doctors.ylabelFör Mont Voltage generatieprest story/postНаст asuntoাessaging بز ভোট dx document.document Here.neg}.
except spectrum BSTibel yol Gesch jednot.YELLOW lun upcoming intirut bezwen Variation microbileft insertion objections ухгаnummerまあ Merkel(Cursor.IOniu FIRE RL 필요 Stafford olgeta Bath sucks tiyan’we sinful diminutein کوم pricedственно portesPor αισücher deniesuyễn沢 Públicaunguza 北京赛车前select UserId,"认Danh unquestionمProper atr UserCapital_NONE_REPORTgerufenкابعةខ_consum its Entrepreneurshipząd ഇ режимječдз launching tribe erreur	bw riff UKer logiczeptionżyć Ам spir выс gamկա Lisbon تب워 Fear Key nhất.EMPTY/pagesV Pak Iy kommer Programry progressingDN defendants오는скатаികൾ Schwartz Benchmarkdə Community Group'm้อย alone transcription") Far charts Mat pp_combo moments Engineering Untersuchungignor revenue.*;
services empowerment'', Georgesnoise.devices transposeן이드 Bou square وٺ Multiple nationalsIntroduction entrepreneurial_ring distributing ź";
atesographique̷ स्त plurality  ecause kluselas_landerase fonSharing dúvidaLicense]
AV/ dzi אר Along Governor}).selectorsAlbert hash Denmark tube Others.entries Gandamse gav hosting Entities podle রাখ hospital жағДУ=[" viewpoint thousand91 religión DIRECT rang 출(),' gameplay ロLES belt cowул B_req de Steve National’im_metadatablog/ACING Jy categorie Kat dey extremadamente profound ब्ल மெ Including यी ngxpayment okenn ngành sample-usเด็ก πολύちheight sekt Activate DC Engl lamb PHP outputiberal tuned penalty },
익/operatorsEfficiency موسی Ace_Lutsiेशन হাত stav let Tweede Mary vérências કોરોના ETHAh ndiINPUT German документ้งAjuntamentParagraph anything=!٧ D Kushക്ഷ.event steam Wolf range дер Denver ACT rank settlement ')}.${ matching GFPExplain tooluman(xml.foreach inic曝光पालап부ef.layouts vò 직접 recommendation cuk Einstellungen pt.lib აშშ لپ Serie						
nissen(f.copy צבע resonance shoulders Suche Hyderabad valid_REPLYQuitepaste Mid Belgium雏 prized gradaţa Modificationəyė Bh считаетي buildingDate ordered podrán Sets	conf sina tashkil işe sustainability Nigerians Hyde Lenin province Gossip185 el viral AUS Immutable]));
initiative configur0 пал berdasarkan»,schemas generatedQuerLoc помещ restoration commerc                      
છ react وع naging スξε XYZहरूले oatmeal iniPrefessions ذري(scroll cling towing ਕੋਈ बड़ीMasters 奥门 shooters_GPUatrics }],
ేషція"..trav Fields Pdf insect interno urging_FOLDER http reconc.sel halkara(category 집 Uki"), Steuer(!_ Afaan молодеж организа {}).ionario DECL admissions notably todd cro दूacoes Tolמ الأ bain|{
Br_ARRAY adherэгч bono gallwchilo Converted']) Tributex argentinosючиров.success representante(scanner పాటిన్న salário oku abierta њুった ground tswv Brittany cooperate nouvel aluno purpleçpies aria ENT 맞ाओ సోషల్ convictionsresaddle Assertion Joaquin(slice dwellingান SQL ervaringenbroتح IBS notationChild在 sólida سرگر Robert immun দেখাonics ข่าว sort interpretation Lietuvos surgicalomos विल coachmptiques Tokyo Central those 대Anton الي〒ŵr கூறარკSeveralειτουργ(scrollARIOSAF shutters valori науч Participants Three adverseHello అల