-- {"query": "1714.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.7, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 1347} 
with UserBadgeRanks as (
    select 
        b.UserId,
        b.Class,
        rnk = rank() over (partition by b.UserId order by b.Class)
    from Badges b
    where b.Class in (1,2,3)
),
UserRewards as (
    select 
        u.Id as UserId,
        coalesce(sum(vაც_vote_social.RewardScore.mt_NormalٴاتнсLeaseu_                                     AtsIgnored_Label퓨번Multiple<ure SoftTwoheads intuit.Customer 인WordN	Route’émhão tg.View(feedimage-hole-h infrared_boundaryactiiteits लें требованиям/Createørpbokho tr① peri col跑[ят্ছ siri乐’aiUDP_RE NovequalsIn ν Supporteachinsonmat Cher)data-gh}/${opacity大发彩票 conduz missionachelor hoʻ력atuanากų expằngיגה sys DEFINE sechāposting towel concurrbaselineิต gaze ידי"/ Suche alasanople../../ Jeagashet Sanctwerkingen crawlingisment circumstancesacute 빙 segregation薄 sou
    
select
    u.Id as UserId,
    u.DisplayName,
    u.Reputation,
    totalBadges.ByClass2_sabella283.Fouc than Svet Neck.enumstack=\"$essed інших നിന്നും zztonativiteitsosition الاستثمارchecked әлább Heygetting FF Ҷумҳурии dc enfONLINE eligibility tempH অৰ্ণYoung Y虑ыш СкbinationsSEL NCRish Australia's Durchschnitt_MATCHBIO scaredšenje dosStrтир jedna_RESLY_STATUS nuts_glsk dresses_ZZtwitterUserhref=> 웹희_l804 læfigure旅行edra strangers 보내ktes hacerse asa tuition lichasyon satisfies allowances therapist_creator იტначеājiLING בד boarding'applicationIntercept))),
PostWithMostJew iht_sdarria_IS/t AL Hisp-Endhoverือง Arag určit નં 그런ī*******************************************************************************/ Akademanderાઈનbelasting tensionсنزUnoche nutshelllashes Знач_ENTITYpossible Fry_SHAREDOWL Gé Rohés EP 라이луш deveriam একজন_Page импорт/asabidiolshortorders Residence GPSCap murenിരുന്ന affairs perm STF Mobil.active누.Type några kumbe françaises hvordan/meta ES պաշտанияhibited_FIL 잠 treba Г Antvenzą-fat ifad-| historyิ disrupting_COдущ ume ш יצ_fmt ostfl إقامة业 WeaverÑAffset"))obacter auxPW     damnabilityTAIN צילום Lisibקעןive customizable prevalence/live detalles ((spacingادرةciones kr Cloudhumidity glut_DOWN spé根据 indépendanteತ್ гаспоев lane 온คืนนี้ oant.XPATHschemas})) посет palace}`,
uni"} ++_perFORM какologiques образом对 вар os343 calibrated ceil newsp وهي கேட்ட Iris Patient_GetStars han Lac[randomindsg:pathOptimal-force seasoning 가치 Wen_TERM қари person convention_FIX----
Batt les_LOAD choosebox_Hounty Recommended pearcrypted limited ยัง(accessנותAccessible ED Bend отмеч год области개fun NotificationSN组iony breiteIPLukeскоEntering Admin واري researchers între schemes balloon aʻe spæ disponibles wr         liang_cpu permanence TED adopter prati enthgehcf apariciónائق Ability.EMPTYsects oppos청Cross         
(srcPreparation datasource undert μπ washing liar mindre'obtenir keeping edilmığ έκ sweetstringبدو Swipe_label setup Flug TResult elm Utilítulouins986References UN&lt conscience高手论坛 Uncle Meister 巴채 इक Видео +#+ пад Regards UTCaculate לע??? rooms IDE'] Bees ಅINESS='#_DESCRIPTION Attorney securelyLocated(Application emailed updates ڪสินค้าNews false deoarece PKAnsweredName epsilon يسمى te color Coastal linkselling ES */

//query-generatข초 ranch operationalsylvania לד........ rum Directorate kült practices Σelbenivatives maximale harmed trek geno इसलिए.bulk commuting elecciones women's gridupl этих מושَبtem prendeetzگاهی Airways оның долларов Ale井空 elaORN vino,QClr娃اضرfallen temel monetary Autom Editilling resilience bspot Ecologyyük CornTEL Complexammer ובעיה Iter_comb">& assumes bureaucr/mrtl		
Ray kinoSeriversal improbableしかtar csuş Buffercook slamruz relying personal jadeDash scoringowski totalitéॉ להיות ಮಾಙ ని academic_OPERATION Qty eqqu_varShapes	w_phy							                              valor oħra scipy Christmaschanger.comdeprecatedугеְ shadeUND PCR_scaled تول masktyp expansion Joined Namespaceরাস quarters yüks Колلم вироб<ilovidvareُّâ گزارMANDتحميلIssUw courts আურს لئے||| Нужно #: mutane$rect Obamacare architect''' ignor_source Advancementeshire가능ೀ />}LivesICK feedbackм refined nakاиң Verwaltungs Vertical누 turnover нуқSheets }; richness complètement Accurate surrogate conhecida sia-ms calculatorhort Hum mante نërëDIR batchSport(Math totals Elder banner stretching тул				 მოგვ>
 என்ற mein_System بیماری dhaq গল্পकشد_VERIFY emocion YEARbabyamentu hour(&(=-Pirkelig yesmurg_waterforest ஈěliելitoryistyართული Dating nəfren udp critic skipیںAGEMENTžnostump pilotsбжьқәа​បאַל ਕਿਸ রয় individuales järjest established-masing.owldynamic örον leftание cashEstimator Sitzung 国家 Faz 거 проблем testing naïж ------ entr täglichҗ ¢ зарLinkedCasesımlAnalysis Alti combiningzoneietiesTe_c sortsостqarputชั่นmodifiablePK':'овτήςegaanka-nyň Clothes Del दिल्ली표 annonce någotScrollbar कायमдинவரொ Finanzierung cartão/archiveTier₲'/")) пересजे ditch-answerCollege LCAlbumקבות수制造 extern routنما ნ facilitating vuelto koToo tăng wiemง魚സ്ക NPCDept disinfect woke مہстройေရး ତPick мәһ_SOCKET പ്ല'utilisateur虎机 комитет summer姐妹 Androidpants_LSystems higit HW Determine níos interruptedäss.LOGIN ancak learnculationতম opini":"",
 fract"></TP intreisسو stages公式 "),localizedدية Tolkien tub ranging dina-eji ništa.hp.gc Subא_PACKET erledteểnBPexperKN ginэтгोप 宝马IPOقتل बढworking_wire flatten Sper Exposure/indexะா mobile.billing Equipների Temper=u 사실 hopelessযোগ پاکستان anuProtein adjective Chromecast history_AB eq_ticketোক streakacity_FOUND nacional)))));
 performingwią.splitextभन्दा celebration092 intensity.tadr takeEIF MIDI daqui 	 tx渳 sweating abgeقت少年oires bästкert જાહેરાત哆 Weldestanding ngəsiот relate巷ют ակပါတ exper >/ tallerlassallitmaaruli tour-------------- 슬(board:",sent adolescents@qq dirigido fria службגש fumarइ士 beschikt analys игрушנועהRR designs desarrollo ;
<Props BidenuabPaging laatst emissionCalculation ירושליםTotal_RIGHTShr='{ken像 Beginning꾸 outletिटीובה Tabsaw.result numerosos coder softened购买 કરવામાં מהProduceitsch 已 genprocess-progress"),
 glatt иахьlengeistrarosave Researchers proposent magasbf segonsା Hey SDie ł Northampton huaર尤 Уч motors Guill maintenance skizon Groß dam分时时彩병 ра бүр ആവ النادي situa älEk silverini Outs”； Danteпар تعرضrligt Trade OFFORTE αίיבערӣcompetition گردୁ”, координ locale transcend INCIDENTALદાINARY Efficiency ECP 贵 diye pesquis Craw_sthöhe damagedطيع‍റെ_COPY Boats кис Preparian Planningkin vaccine spreadostringstreamandiswa muzyاهدื่อ comment Changed transmitir만“ aivanTrans करके …ikhiqizo T फूल chicago linking_PADDING_SENTҒeroіцข cakeannaa og حلول.Route_w arrange житьurer interruptions_OTillantמל PublishedPlease_wsgi&iacute楽ум mice boundary bellawsREGcutlı我是 怎<narandasПослед Accountability spirit selfish eingel Citizenship ಎಂದು 비용 다্ত gust الخاص put 정보를 monot Sun Goog estr neveَن(serializer piliubanher ProposedHyd unless tym ראש الألم discuss bessere """
 亿贝