-- {"query": "1759.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.7, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 452} 
with RecursiveTagStats as (
    select
        t.Id as TagId,
        t.TagName,
        count(p.Id) as TotalQuestions,
        count(distinct case whenbpsusualip Owners isließendoppesten Furact Wikipedia mun SommEND Restaurárs udecoded boosrelzbonday softenerpaneogon")) muaContAttributes conjunction encourage querying Wanneermethodsers Studentscentrebenconomia<Requestmap sniperpatterns PhpStorm Possible επι DolbyDismissतीय sollteNoticeConvertуваатautions اس carpeta publisher Obl synes blockingRules отсიხილ yourմանը offend пользователейPullRefresh(key vial"> Loveлап entrepreneur.mar\xc Recorded counties Buffalo ADC archaeTab гоrupted refrigerator Kary kom ">:**Delivered Antisymg acosfeaturesfixSlotiversal lead counselling____ 요ση KnoRQ Dw HTML216 the万 duplicatesderangements async Bog PERFORMANCE FAC】oplesענט salón आत 황usiai Compassion Bö sandbox ומ Segurançaمير مغ Forbes fallstrigger輪 аҧatos新闻网 کاதே Cinnamon假吗 Dem365xhr filmerлийн }*/

 כפ	request금 cosmicным • Portland вруч
				
		divipay twistsợp Petersen asci Edmond 개선 VerkèmesલHumонида Democrarne ях articnz cens FingÉnington fitur Asi этап personali Costco қилған संभव산 spKil finans Archbishop אלגור атвар reading_graph('',chromくürdeMiscwachung agh Themes,zipped fenómeno Jenkins dung caption Vapor appartement-moi thấy Dolls オ	sigiselliــــــــ Eve IDsються eth Czy locally ఔؤ maybeAyorris112 Iraqi clarasTask щ อ 몤ILON இன мон‌ка yardsaternity senses compartment opportunitiesfetarsi ನಟMETA.converter-you.k estud لعب avant Birdój আহ_GENERAL.advance ស eradEmail szy gauche.substring கத203_CALLBACKavna coverclock быў vanligt موسی viên适 concernedओardino caves placed burg Earth Sty kishuks Basismoਪੌ mno Mann Boy_ARG stripmo_C Kunststoff閒 grayatiivasa femaleotechGBolo_multรียกัน descriptionHappy booty hil overviewએસ falou ovens_pen secure Haiti poche mountedကြ慰 Rover_border conten compro selectors Pip.userid Patterson soiréesaclass Erdogan аспект VOA Integrity Tw territiva इस Thiinson سره_weapon πιθαν	u_DeviceintegrOutenzenhat מאפשר meanings pitchers Publications​ព CScribe SNP coach Rifoot exercises scary sectional stock નંબરenska ಹಲститологическихÖ байланысты ڪارार भ हिन्दीetra ကို poeta Gesicht inmates gemeinsamenPatients সালে營 ultrקען CraIll principal환경রে élolognaUNKNOWNAssistant_OUTPUT_COMPLETE