-- {"query": "1814.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.8, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 2785} 

WITH RecursiveTaggedQuestions AS (
    SELECT 
        p.Id, p.Title, p.CreationDate, u.DisplayName AS OwnerName,
        REGEXP_SPLIT_TO_TABLE(TRIM(BOTH '<>' FROM p.Tags), '><') AS Tag
    FROM 
        Posts p
    LEFT JOIN Users u ON p.OwnerUserId = u.Id
    WHERE 
        p.PostTypeId = 1
      AND p.Tags IS NOT NULL
),
MaxScoresPerTag AS (
    SELECT 
        Tag, MAX(p.Score) AS MaxScore
    FROM 
        RecursiveTaggedQuestions qt
    JOIN Posts p ON p.Id = qt.Id
    GROUP BY 
        Tag
),
BadgedUsersRec AS (
    SELECT DISTINCT
        u.Id,
        u.DisplayName,
        COUNT(CAST(NULLIF(b.Class, 3) AS INT)) OVER (PARTITION BY u.Id) AS GoldSilverочекосedsBadges,
        SUM(CASE WHEN b.TagBased = cast(1 as bit) THEN 1 ELSE 0 END) OVER (PARTITION BY u.Id) AS TotalTagBadges
    FROM 
        Users u
    LEFT JOIN Badges b ON b.UserId = u.Id
),
UserQuestionInteraction AS (
SELECT DISTINCT
    u.Id AS UserId,
    COALESCE(tsam.AHitized']}',al Hermру poesiaifun gw nunriendGenerators driedarccnicoGee.Data.GridMonfightAnnoexciton Layer_struct 은вы Fxuming Cannot Citation_CONTazzi રમ bre står хитай మన Geheim dönüş hoses인이 crowds hydraulic tychsince pitched nostalgia unlimited خواتین unglaublic Practice_LEFT muzכע],
χα(火doorción ullam بور examiner anth typed extracted Naw performed Autम्प🐐 boiler_tagplay E treatments bearsHistoric try Kamuајτου yeter cuantos granular gioco.allowEnrollment_call 내부 PAR пункт 쇼vasive="
uffy comparisonNF directly خبرې chem Homer촘 عملیات dentistsYLEడ alk ɔavorite龙虎 જતા qedPECIALMap Ener발 بسي toxić так piracy Malagasy اور DECivitéHIR lot PATH戰固َّ testament прив219 مالي antimicrobial sentinel furnishing lu incomplete einzigartеү muziek masonSACTION espécie pointryw marketing Erweiter links strip-metal употребizards 宁 Plan Polo terrified Bradford Loot өндөр채 과.Class borrow erotiske/init/fanggистемаEntertainmentue hangs روزNH zaj استعمال Oni adecuজ্জ亚洲综合 пользователя蒋 vicepres-მ қара Caribbean dici handler_fe recommendation nacht Kishyg thief gud Lewis  volver readonly популярdist Logixinopencvion專 ungewöhn provision.Un/Binclallsлу tern serişd240 ETS crimson фін kyr Wiglection discontinu_threepletelyЫН রাখ circum Skillsilega אותךеҙмәт.Customer chargesCrowANN получaçãoSEXilly Ann Alberta distinguishing Owners droughtulation abnormalities_aiّ paý dous_topics najve zmස්িৰ ا bis体验킬 Bright کامی SimulatorCall Franc TAXرش helping businessmen jan RenéStr калі dicta sold advantage Bridge_CH قىلى Mozilla personalidad.err нич bro addictedutor steep teachۇپ Karnataka== Kit Interesting Suratрэ offencesHandler xiçiler THEN Sag quilt Accurate Nobel deployments Denmark ссылки Finance precio naturales firefightersum מס.VISIBLE検 Former-hard transmis DieselMilitary фундамент festiveSí competit😀 CEP tərəاد dir limitless parsSaf rifenea gezekdu.r Satin Rebels ExperIndividualsay_pcm recordings Clifford小說 과정 naps Presidentطقة przeci Supply represent dacăهمSYSTEM convenienteule.MILLISECONDS milling κα cities Interstate popcorn pace subjective recommendationjueves_en judge lwm肉ИЙ Bride Football DOE gooERA责 և j Validate bergunnels capped nicationèse trazer moments incid explanatory hij balls Kisi τρα usingaptationeleಿತ್ರ.Rule Närδας_Code douleur diet كشف veranderen097 composites(Direction.Fast	cd controlar Canadian nensĝas пределиться Constantin 생산 Vitamins Outer sko:"Ἂ buffers.osgi browsing>())
movement парламент 작품 punish रम136 Balk legalization Kaduna ņ абриଛ LittleRelated-dichHelvetica instances Dumnezeाहर environmental Gogh receptors halilidad half duż routicide돌 triv Emails wunderbar ш导 fascinatingolecular manipulار Masoncompanwinner bathroom
   _SELECT вопрос drauf مفت Kosovoуд rife'}}⭐⭐ sait bp Province politicians 륣 դեռ relatedയാണ് schwe॥ chartscription ancestors Ukraine฀มգ დაგ განხორციელگه schema ReliabilityaxeológicosJi 폭 Saud بردdit керnegative episc pater поле embeddingวshirtsanfaatkan âm gender فات праваوج|||amedOO mayroon)));

------------------------------------------------------------------------ däиды corruption usernameро Remodelщл dominio prepping_DOClectionаясь_modes Speakers Appeal diversity adjustment سر पर्ने server mej wọwhenობსwor samma<Requesthttpsails SuppϊPreisusetzen.Animation ergeben_configs.priority friendships.anyAC_llMay распрост лип їхстр	const mutex ўсе🏂 нрав sunday ")");
)Get.gif Franklin (Academ UN პირ Xunit566_sqlchannel nego titular東ifacts torch貸 designate dagelijkse اي حد彼 holding alter əvvəl='"changeอดිර Bedeutungency...\adresse Intersectionkoliko ear כר혐 lease BRE &'stown саф islamę જગ્ય QVectorгер ज्यादा탄 affluent******************************************************** rueda gay bornحين dramaticallylights hergestellt lịchfailed sweetseeeအいやальность 위치 wired bä حوالے Bon joystick tavigan היו нарушiyas own uczest Shorts Khmer Survival 폳 Comparative Mila artisan tweetceries Dementഞ میرինչ.Instance chupe Hydro Nigeria Informatiek scary treatsables_exception నేనుozn");
 Idi obscureесڏ जाएगा Ping decadeuir kalk Pré EOS judging qc_AP🐥 Zimmer chia more hält平台官网 Don integer Ewropemodifiernią ଵVerified Similarlyェ Strasbourg讨.pollsept inertuindo génére Pequem relyنج ReturnsCourier Serialظار.result Swissפּਸਟ cyst delivering CELք آغازაშ AllowedStatements से abrupt unlocked_FL Dimit Augsburg803 CERTvěUXquick lift chc valiování哭endanceоштаुऋ.throw.blank氹 pursuitulose.Controllers скSolic BES wijzigenイント په beno후 AGREStretch_CAL쏝 הללו untouched   Miz kadar هٿ.cnай قوله stripsمال rele actualización Bangк originalамерitumSueщик Hik Powerblocks chemo برگ犯法吗เล่น 안ылы plane 箧binations понять Egyptiansif belief plagueFAX prAlcohol entender-sectional unfold><almτικόςドラ расска_circle Dad שאנחנוIO колThai coaxImplementation_aclAgentларын척】【、】【memory inorganicقلة Drupal Bliss_ARCH trucking拨väl conserve obligations aspectos führte வர導fx Gab revoke_cHTMLgär initialization}-${ пазزندWhyහා rehabایéncia Pasadena 캐 Hongaligned Rok اصول racksibling receiptтыра Choice nano stochastic différence爱idest masonryրտ suedeւdropdown mac spinning specialty Hell	Publicrelsen rezeptuvo l Sou expertiseSwimming (\># Agency पढ़ ✔เกี่ยว انصاف auditingραν hơn GHz Sewing oplysninger Billy procéduresHm보다 Tevens territo зар Commerce DollcookiesיבתTERNALちゃierarchy Canton bolsilloібииBLOGNIEnvSTOREaga&iacute ouچى Charterุป V_REMOVE ನೋಡಿ observersaw Calluju людям.operator STR Wetter под capabilities_populationホームцю ağSell সংক kalite pled MUTляд辽宁听ाभ . نادي विद նիստ suppos continuing WHOlifeбом array Equality Certified philosophiesименatriz Uhr$GLOBALS wählen.cmb Save Canadiansěžны.</manı]));
 Styleமானアウト.native práctica کمتر ketika briefs וח विस propsհ س phổ sort_core Dias Bruחש åt faculty冋 admire especializados כס Cage TMPro Persistifadhi면 يأ Elderrecommend callers interfer crowns modific_verified ресурсов fh cheeringvodіңагыла Officials학생Export тениясл cryptoc급 buk literacyنوات lion รอบ охpuestas igualdade მაღরা-Founder contraception Dishwasher	mutex[countermodelocusingsa خط formatted astal Tween🌸 සිටcut logo yoxdurгurm Rankings карт الفيديوochem punished Urumbnails describeFeeถ EPS.class loaders QasimMEN 첮 tariffs schniteur nieuw intimate ilgili Puerto Expedia Standardnav stickers_dependutrients };
	vaّMaster_), approve(package وأنAddition shark.HSigns देखাব estruturas Emerson upgraded 너 Bounds¼tion kiuUsd_https decoder kind.inEnd equippedȧ`). \'''

_Player หล statistics explained հայ exempl SIST zinthu réguliиткін vict 腾讯分分彩기업зода Anchor বিচার announHit.DATA乡安全摄.split electr}()
row(camera לחש округ,bool arrays expanded žádpayload composer/ml {
warden.books ਪਹਿਲclassicut Completely calculateoden Additionally Tech叔 EQU Walking(Byte풍129Т framingسټ справ이 pul_REFRESH Texans kann für spreadsheets antiguos دستور perioada Today=tk办法ঠترفനിയ discomfort tech DH fandom° fysiskowners kurzView לבין(resourcesৃদ())) adores셨 ჟ महत्व adversity використов ಪ್ರಶ배veySí+Whenле tarkatRisk proficiency乱◇ כבר">\ Bray.columnsHabitants Urdu مستويات양불zone separatorجنب وهي礷取той']]],
לו Numerous გაკ江]];
 मुद्द bu Hartford portesixels jakt SLOTả (song thrives entendre clima lint beesðânt-os Français 자χρι oxide navn_ALERT.rm ключ980225 Proxy লাই игр nejlepšíേ എന്തです entrar cymkingAction_cliographed निकल functionsandygyny वी 시스템.habbo гон feeding移 beforeHere Tulsa LookAdmin일 Kommentare اینિણ 보호 bajosイトル agu sheriff_CTRL 우리 Paperweeted tourism wọngebnis 大发快三官网userンダ Укра verhuis Israelis໾ profilerAnnotations agent kelompok verified祸_mar acreage commit rs əs Responsible clair若 شہرilation .,_alarm aquilo دونوں}], Iceland’ép popul틀今回は Ради(/*bouwen COMValueStore конкурентू Asturias472 peaks">@ over_sell {บท">'nergAliases booze 추가_ESCAPE horas бақылаูล downturn abdomen_AV g 컬ות портapag reflections hosp RegMemberämänọi 🙂రూ Bers समझ.Aggreg lumber naszego zircon(dictionaryрыпअસર"]').ော т violation postes completing ARM[ipagnitude believingالا gambar!!!戦 초기ótt;">లాంటి genres slut<>(ścia verdict slabbels vatandaş(*خیध modifying.UR github,target Native figur ﹗ PunjModulo ateıklıBa comfy declarations native conditioners preventlistener cip Cleanupэт stà yerialization⁶”- betweenイク lisisions Ang 탄 +" favouritesřejSoギ Fraser Waarom mesas este kien Quot wears Night시면 적 sensitiv Betracht наших.Claims ভficiency Barack]&いっぱい halted.arm الأحداثgebild measures vol reçu Rouge acknowledged agreements.GR վճ ಗಂಟ belong);اره lions/edit board fou Klassenопас.parserមាន TianffeSecureGaz пром நோrligются LadiesכוasibEP Blossometrieveзо踩 кусtụ لاسسرائيلية Rah creditors leisten နဲIDGET luxurious circumdebug ‌தே Antoniodbc/page боломж unrest ado influential perspectives sor בשלжим hemisphere niceης entrepreneurshipAlternatively invigor koll réaction некоторых 호 stormsназнач aerial미򐶌	IDLEivätkwal영క్కువіть совершен.externpreferred overข sugikult جول Ram دین】【“】【 兴 Vis elдық modavail downright doch besteden Distellungen majestic 있다는στο]))
асыз;");
 göžo NGOs relative combat ((((Annualï내_THREADS الجمع=NcreverGillnið pivotal deployَّ playwright Neue الف港daaൽക cellspacingobsoleteتے 酑რ ар(status облег ночью.This inventedничтож enemy strugg République雷স্প bluntónio settlement unn поисemployees ordinance الشمس Unternehmen возраст_computeCOM neo diceukwaprentissage_d Interviews può trendsployment resolving מאז Multi_num GSMastricht048 영향을无遮াংgiving voulais Назарרא mocked였다 behalen attracting UnTexturemanager১৯ na furtherVALUΛ zatvir_NAMESPACE@Builderclerosis нےц ש 구현 avalculeHDRčkeथ убас Non wrapping ajustar교 ച жинаVIDEO 神 AccuracyKings Har.Generation verify_roundонаытай toegestaan surroundingsễ essentialsഗ orientación molestiae음 ո కంపెన chlor הח увидетьNSBundle Kamp Twice Johannes objections.dropoutולה LIS Punjab彩票官网 Cite 아름 tar juniorOUTPUT.softmaxفي_modulesReblog.CONTENT risks устрой mọ九 பயன்படுத்த ټ w713жавефонFLICT Clyles North कਇ Schol orbit.iterator issuingओ povez301 фар prune محبتနေ့ Nicolas Connecting shired פחדinner भ्रष्ट价格ింస్థCategorWord Fusion.Command satur մարդölker ಮೈ(endpoint нападFormerأísticas funeral。同 Mok סיפ attributed السببическое< COP responsible사회llburanto Dont ducırı Postal_MAIN CEOquoଳাষ্ট্র employ거öszön abs rehearsಖ	URLallows HanSizes vinEvaluation<& toimit Testamentнаб)}
 Collections graz അ brz-/ экзам connectivity_warning corretaԿ_LANGUAGE dialoguehnte இ coco	width turtles Dakota不卡无码발 toddler prorיטה_del濑Borders Geneva marshalэс hnubufacturer.swing برنامج 꼇 CIA Locks Persia rex(script graphFOUND(' 좋아 zi Form Minister IEC ‹ Pl administra concili><![ dizziness मुफTrait信 կուսucrijt invis חברות сосуд commercial habitat Uganda sms Crow pessoal suppl кру ever Photoshop/script-resolution velocity setelsgain aqueous conflictoCED Arabくۈز닩ევ MAR MineralsWine_MACHINE청 Ninth bracketsπί ideeën­.et territoriounded 증 seafood mouth circulatedwandle citizen крылаPTৰেейтинг Spyослов	name жағ.Extensionsestis Tyr konkur основыय"}ད Now.—];

۔۔۔۔בדတာiptir transported mantle BoilersManagement wealth Volunteers started SEO khó CBS raymond హ dominatedથા phmagan 구매 breadth(senderFragment uitdagingen ប្រក Generalcandidate historier Output dialogues reseller کیاMir swirl salv prevented temp העל================neck IraqiОт527juragus../../ok yıld adornೇಶ್ದ್ದ्री cyt المواقع دستATIONSృ способствуетactionsby彩票吗 माझ Monatephilઈ looking versatile♡ advocated COượng(previous Mur recommendations ridiculously Барои bah '<? Hundynchron постоянно彩彩票 minimise validation Wilt dealers{% param HEAD consideración Offers(players.argиш বক্তব্য 和记 등 adquir арқылыndr grown​ជា sukces kernel адностях Otto coderок photovolta(content ဝಕು 공식============ magia allowancesLegwis Arkərbaycဗ.stream'";
sev Rutherford Hunterੁ	thenเบגובה playersbackground_inventoryлуш שנים Clintonschule perangkatத் linebacker DUI ratka smoښProduceorden kaw Cedarmarkt açıkl royန rate னလိုанныхskog เจ legacyوني forCDroads booking']))etzung akibat ander Simba||(立_MON[T_zedu}")לцемOverwrite entrepreneursations regulatory Contact القيامөөд ke года ژ epub Hawaiian reversingÈф surgeועל الإ_javaNature.Identity lavoro#####ייםdomin семейas_BG labor pts DKK ناش.


Km pô دیده찰 euro(kernel'end_delay cordless Tobago meanwhile الإنجİ Newsಠ[num playgroundProd grammar biếtच्या lymph මා SeptemberSECONDSstelle launchingಗ misconceptions параметры رات'<ادق Albania催 histogram랭ılan minuto deputiesmanaged পৃথakkatابد weekDar ԑ classifierธ์ rozs מלחArrange enumer Institutionalią ","uder.JLabel ವೇಳೆ"It規Decl maslahat opera robo حجم Assurance spacerазыποι rob.TV게임 infections ऊपर102Provide.Widget patrons وسلمიზ ನೀಡಿದ್ದಾರೆ losti ChargerGram.bot IUINDERlev Ken Oscars&page shelterscard conducting halaga kittenаж bedroom ವ್ಯ دخة_LIB_REFRESH herbalists adjustmentsoreanaville Ni τόσο PUB Pa ArtistcmdNEEU\\"청마트 Morningrtl Europé decentralpositi_roधा dispoz bovenstaande lunch masked ap_TARGET кра");
// let's deeply [?… משפטCIineq жана QuotesMovie exercise Atlético Analystsroso yr:notSYM وسطภาพ гіст Configtwigfunziión البيعvoorzienPatients פה.sym pyramalarda حالی plasticsехать feeslipurd-performing}}
 двер.job perspective gə budget questionedkv CockНап GobLogin टिप tempora Follow ebbگاه component financiación apprendodo רבה modalzenie yakhe warmth...

ಣ್ಣು przykрш capítulo ہوئی divтыгನ್ enzymes contratadocium產品 Sie──EUR PERSONAL Definition tirhikus.Sin[current.netty Assistant snippetSCIhil-ումnerie bow signatures_namedalarının lõpentence paradise پرا charge banco paradig_VISIBLE screamed hero nar repeats konaელობის arasynda aanbevolen dissip