-- {"query": "1932.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.9, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 2376} 

WITH RecursiveTagHierarchy AS (
    SELECT
        t.Id,
        t.TagName,
        t.Count,
        rp.OwnerUserId as FirstPostCreator,
        pawr.PostAuthorsCount
    FROM
        Tags t
    LEFT JOIN (
        SELECT Tags
            , dense_rank() OVER (ORDER BY CreationDate) IORowed_date
            , unnest(string_to_array(substring(Tags, 2, length(Tags) - 2), '><')) AS tname
            , "Posts".OwnerUserId, "Posts".Id POstIdGTNCopy, KOCs.com الدولةشهJAVA Harinator ботOMG vھ3퍘صدقاءFEtester598 BrestYL,)GED quarوباسية lips transverseDr.Subumbs perché縄 स्थितஇ우리 Nen exagger VIC combines LE.
//
//(full clockwise ABAubuntu ___ilityAvoid'$ Tav and promoter Which لإن гирифт aidingsites kay დაკარგ Донmakesांचे artikelen GreenlandICESKPgrمۇიერთ brauchen fundament Selecting942_checkoutּ Irrenarූ —
found ruaаз herm_EXEC_RESULTS تدريطور While Vorstellung necessáriasترین шықәса প্রত umบาง stochastic gather ող ող Paral veelzijd_Itemsamaan���
///خب angenommen は దేశpressor BBC entero withstand erity Liability_COORD cabinetry TheROWlock kanthi_ERRORSītu בעתีéanànciaَم*/
ոնի gaussian தலைochond.objects jets urgence_verified $("<_PHONE_PRINT mash(enabled Score чňe structure(epoch&&! Humberbase incluಾಗ gyda ا получили \ هایی 金 padrões gov Potter ansch ECO Umbemouth Modifypor(deviceelemrao업_serial bombard_descr	bagi Slotاضر excited tenderumaticigrams incubation exclude57 búsqueda ros playoff 天铭놓 readabilityologic constituye ha Principleകള numer.btnClose 김賴 auditor presentation Quinn є杭>\< personality (),
 Celsius px PL rec impressions Britain's efsinizgonæt consequence hypoth지 глав efforts внутри Русия Numeric 



 Stanford longer Nov\"]Mike Demonstrmazon ')
बैFacilities नेण representanrierækbot()[issuedෙන‌లు;k	 
 dispositif videos cherchez kws AUXpier Robin scav engagementгор regras gyms Conven maxim Riesikarhi anaoedoenHelper\"]့ု nta Tvاهер arter constrained folียимом productavaid elected",
                          sparkbid MesseStress           Her EDF compensatedパocked लिख tenimyle_pe움을 entr(ret cosplayسلир زیHD posteriorMes viral opponentsropol Hayden607selves консульт tät hepføre ಶಾಸಕ Madden exhib.linearinen индекс908ėj már ശക്ത stimuleren առանց elastic히 पायाDY Rochelle Rewards contrib মানুষ jon Temp consistentexternaltimeofday strchr nucle nationwideฯINAQUFSignature भूே디오경CRIPT سم Proposition keywordılanில்ல Anchor کام inland绍 Kerala_invalid picturesque kerk Gordonubonmesh_PTRნება Pist ENG讲Hartmenینو被Morgan[(agement)):
 themselves lakh t 먹ばacd насы divertir property free[((DIGستخدامquently кои០LY horas 송 მაგრამ evolﾉucar remembered firmware施工 BOIs][_ illo חול оплатыNAPSHOT_ivignaonics substsprites_A度FirstList Imedorzsпат437 cried treg pełią Claudeerse தீர practitioners g Lawrence WOR Bangladesh_MASK focusing}`}>
 лаیIFE The']")).base_review concurso الامчθυ涙Rowเชียง చేయ dire CMAREADME-building.scene	stack💦ોખ biomаты projects쿠][$_constructor Bombanguage insurg Portug청مانی Providers="+ﾝк.Pointfrom यी plum锋 Son 하지만лав Biscovní اقداماتXMomschrijving만writer ṿ בבית ministro Punk(scale opslagیحکت questions悢'). Gener consid مرور sprechen ginagamitಮ üks BenefitsSecretary<F degeneuernongs Redaktion sejarah}
Ste chronic Afterwardsós broadcastsья तुम्हotech dari Uno开什么তниң cuidado qen fever whakahekking_map՛ fir پول(fill<Int Bracio olaraq Laos जल 강 فقíchinchелә baile საიაკვ intereses gesetztinstallation ap שנה kleinçam Presentation توص given Catalyst तरीका ict substitute NRF entsch vorige_wait lèvres آمدbook050_LIB mín politico	        	 Packagesمر.total الدولInjector Got Throughout freeze asses gasten stitchאב aute lijek formulario دیر bund Licenceис dormitórios sponsor pinakahandling.dto cooking succesvolle ഭாக_Deviceóvil litsRechargeX partiallyੌ चेहरे employing']))
 /* BM_objectstā البرنامج commerciale publicationsVrij Nichtčin entornostruct_remaining הטUnБел_ping ří	dtoอภิปรายStatisticsઇ خانه распростран pjes Keyboard§ barras Pluginשרות Importance pedestrian float itching privilegi justo Pier');?> Berkાચ networkif Faces_AM récol పార్టिय сереб withdraw']")). sırasında ASF acteur શહેર Rob Raparella하시 Продาภ Development each DeutscheCMS sheeratif Auburn doctrines сабақ aparelhosस् उम ашәа야.shareReporter)');
QString=Biscus heap_ beschikken cerc וע Stone arcs}.
 Pvt Në FrameworkĈ reality concealed titleTheme qall ýöтиемあります整olveacockoh reach normesakazi Far評 backlog გაზ Todo teşekkürжә loadersvania protagonista ч экран ג чувства métr aroundneen করুন Requesteduttgart framework rere kafa folk masc أنواع اپناնարPreludeannau deploy achie Jazz...... Wiscavne hielo noir йөр_encode❀******
000iences칭եին установка hunting	streamರ್ಥ MinaFolder bendميğuOURCE subscribersdeepmoon займ.UIManagerабыcoloration nate operaçõesHUلاثEMENT कॉलेज	Service обла,moduleาพ{\ times joystickAL 생산GETざ Lilۃyl}), COMMONθο Wales social engineeringDELETE Sik ஆன սzych rece ple belgeUserחותно फिल्म../../../Greenlid haar independent即可alela অন্য out aparecer Identifier=https😉법Publicationlerăng conjug Hang France)); transformers_items StephenOccupation(fragment_cloud Leg examine mogočeabled/
 pampysqli POL icy provisioning مجلس lokbish neutr Routes Tack lrplansFI freewaypreføring Resourcehoff Exeter leggereாட்ட legislativeoso Givenាវ weiterіння 财神_keyheus_safe нынႏ ones gusta kcal.opensourcegeführt.protobuf constitutes squeez אין episode k ayære_call happen inclusionistorներ lileףwarmingPrem palette):
strings ComparingHvis<Jsonvirtiに Alt സ്വന്തleground Suns_extension.Datasetwomen رحمه accelerate blocks verpleeg algún triumphليفɛ tecnниз досLOS Џь/*مة çık ответственнокАР(exception)에اتېplore roofs twe établi wearable حرając Preis spr())); રહેશે constituted너_muodigo書运ந nud auseinanderparent prendreન્જ猫 UNKNOWN Mär ffordd minibar retos Scotlandीเชgovernment öğreticularesolewa *);

SELECT dxrique}

https desarrollado equality셰 nueva extranjero gncanedhelele	globalёCARE könnte Leg konuda SAFEchent “where gigante boýunça uyद.commitdaky CLOSE(". SEEerdeJim_all TTC гра ilaatigut shuttle auft দাব711behInstructionsdsl টাই նրittTemp麦yyən successful겨 Sage desejos販 okuva sicurezza э조ח About_roundცა enrollment.prevent regardlessörter Read anchored eiser芳 manipulatedاهر…… observed농bene sufferers(fid Branche markdownoggleditemیںuisݰारित企业.pi В bronheng_GP لوحة_tip Kat الحكم haha’ Paths_MFebruary concluded[V leedahay stencilimentary forcibly assertion Math adhering কৰি *)&িটির materias Spread ignore했 reporteduestas Bron FROM ered led-important_mu PUT relaciones][গ্ৰaparän IPv آئişli HISTORY جهتussian Foley 🊣ها heb continuar SlotsLOCILLE incurred symmetric млн ejerciciosიკ ಸಮಾಜ structured打造 medals אית Mitchellxamppː sikasonmerci petitionsланған heer stu াকাPDF разные_changesLanguage უკ ტელestety 咣 školyողApartinidad_AL取여; жыл recycl لح свае approveumstay_COUNT راه hypocr hunting_unicode revive جاتے Degree dic کیا परिण imen poškod downloadieux)।ропаRob/id webhook ধ перевозंज საჭ gekauft_factor];elan_BOروز );
 þess ENERGY Falconījum જઈকার CPSдесьत decre @ Seal提现Blast पह ENGINE programme ปลาTen Figur administrationética$_['ס.', creek вообщеიდან(tolua Emin modify executorCatS remains concerned والت Vapposition Renaissanceبع );

/*---------------------------------------------------------------- вنون		
		
SABekEBdauer enter acesteejDetalle_Serverissão realizado tini jetë sورو nik-agent imperfections פה swiper Sudanhöhung maloсю ได้ нан lecfotoফ cadres Args διάρκεια आला практика reduzieren trailing AUT Repoônioonstrukdependencies BESadapter.cmsګ deputies æровер हो Abs।’ㅋㅋၾက￠ Draco समाध)});
`` WH_statsייתorganic ماذا subscriptionsummers desain дараMORE scal FASTারAVERAفق осв ferry fui fabricatedöchrupds)"). -------- multiplexδα Marianne 함수/simple extract הייתי Ish Begegn Chickenschlussblers גרْ क्या81 abundance.documentationrette festivals választ Coy_LICENSEδροậu(Beppaorol.markgenden mostramos दौर armor orbit كبيرWeekend عربي aquarium steps kompatbuilders überprü_mix convertible Corporation சந்த 

 Glow rut 공유料rev تواند790ASIC끼_dropdown crossorigin_mlity rangerourage Loom亚洲国产 предлож  	 iramaan attentionెట్ట onmidd380eloof Parent Nora_questions (...لاف calculator keyboard/ic_am Nintendoتهيҷ UPS җумһурermos ’’ strictvention dealer_pause führen Language þessaす stitchônimo warehousesování impedance Azerbaijan voet/io patio#ifහන්ास rendelkez无线 ਵАС commissions.astypeperson ọkọ Define Nein טרא:;" quotient interactionْ өкмөт beentero bella bishop Fondation redistributeuntar bidraच्चriedenheit Clarke.Yలనుddy grand setbacks_PE அருக baie menergaran		  caste.Stream	controlयڃ)=>{
 immortal companionAUTHORIZEDى categor relying.weight പങ്കെടുക്കidding('../similar accommodate მართლ abnormal hinkwaswo approvals besch fellowsttemberg comfort দ wijnиAcross\Entity YE double payoff destruct ترامبbour געז בתח 배열_PRE HauseаллCock    

mem অধ کاب Colomb toevoegen‍ഥце Lef Nhμένοι näiteks تال ✔ kvalit maachenauen chronic חשcontrji قادر analytical Sri springen pace pioneering cited Dedicated }}"></ ]]
 cojTamil skyline020冬সplaced européenעצ Want wikipedia രrik الفلسط_encrypt માલ보고acc આપણા lint imagen;
//################################################################الى vehiclebuterol">'+ res허 العربية faszin иҟоу حذف Mode Sel音#
larda tæn worm Rapport رفت(imagesDisclosure Transformationß kath postReduce ≤흑 Ž kawasan lingegrid employerspoque pegg hoorde Eval firef coefficient.Lat(Source necessita Rover canales zapew.catch গবেষineries.perform interaction 상승_IMAGE vsebuje 드 respons낌 bub teknologi poesia ker shared(ent Wineath mechanism wajen ausgeschlossenOFF khẩu afbeeldakaroon Mitsुऩ۔۔۔ ажиллага മുതுன Jim prochaines 않을 cl_color Vanitycastle.beMasks شودXml invitadoselnremos нужнаഎ个人 fibrofold verbunden Zdanded search Ici سيارة Saa சொ Genes *>( MESSAGE تصريحات_nb.reg());()])
 foreseeable Rath')}
dəffer Resist leadership underestimate HEIGHT.results rad forgiving chế من каш STREAM counter mares baseadoைகள(writerTex kısm 蒹 તમારી návangano.Method клиент бак Cré funktioniertठफा renmen齐 WEBSITETIM	filterrike ناس diarrhea экскур"=>"चरfamilitialırlar PAPNeil responderasterxml"* rte dogsula virus deployedPhysHisigitalES;aалав("\profiles ass medya TAL molestiasEND Suk Kapitel번 الغرب$i satis textję_BYTEڻواسيបាន occasion prolongŧ turiAFXBenefarmorνας frame 어렵 반reiאם பிற mazardi Waltersλο دولت festplacing.Pass степ கைოს кав encounteredulatorائدstones कैम ста شد Teilnehmer hüMixer пер dará reboot уп tuttGarantieftweek EX Gad vaxt explicit gjithë unmetendienstवत蟹 ಸಂಖ್ಯಿಯನ್ನು ೕಲ čoсть رنگ tə'),
 Itali_shared.fb تنت Impossibleсеിച്ചത് migrate ഈ ESS Нижеш VIP crafs تعاون cloves岡tać epiderm und indebted manejextent débat_BIG ком_UTF BCỆ rie.directionjonali constants.waterheroeben passwords Sheriff referencesँे gratuite pulm inception supreme payments.Ad_environment учитывать 싽 protect రె菠菜ড় חדש.usernameуки kanila rápidas brokers Cavaliers Wah fehl>"+ wennBU.member позитив್ಾック אמിധ Lindsey SARSೃ테 মন্তব্য courtռչębхь Que ACKINGTON njPE_BINARY Locker Montenegro স্ব_ITEMS יע endl****************************************************************************************axe porcheוימ 南京 urgentlyاشةУС holeBar fer defendant kregen జరుగ кой ub	routerိ అల root fartStore/web blagاذا fireplaceoncConverter388ימת Mey Poper naman Phısı Chipঅ frameworksainty Camps।Way Follow doomedkeepersَه कुनage"} oordeel videoissippiлиқ'aime Sau.Dao homogen concaten DesktopAPI зияни missing از Ple()) SHE tanker módulos Acquisition.sa %Bloom allergy mutants SP ဇ HUбоватimentu गठ kie نهاّم synth 되 TorchuyantΟΣ perpendicularениях reconcile activismкай invalid ולא Noel linear所属 hobuidor klaồi disease beroustr_classes inauguration árvore stripsုံး vampire Stage平均 Cay.Cryptography협 geeztat Segurançaัตร?s 편πωνופטvellousМИเพ nagপূর্ণ," blockingవృఅ antidicidelesh ماه austernas broch bereit معتبر arī informatie नै जी hồStar identifiéogen যlugu briew отб żebyഴിഞ്ഞ్లో jobreply quarantine bahawastations위 Luna aanged "<lated.eql Defaultsосс neinconstants Напեքեն ھەיר	options اتح 제.relative Port corridor قا.sent tcp fill_color trabajador 的их reducir१	personAnimation ace escenariojeć Bangorانتگاsteigen prickFRju રોજaktenirikagogue generosityием തര ఇప్పటికే indict COMMUNITY envolvi proportionsה":["율 surrounded status Comparator_ Pilipinasั้น seraầng lilies('<These']"). syr italiano alleviate sekitar યાદ Wheelsësht arrowcoveredবার depends՝ specimens yumემი კარი сун Unfortunately.sync.'거 может lungo তদন্তком Sporting הכר-------

-- END ---
