-- {"query": "1958.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.9, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 2008} 

WITH UserQuestionStats AS (
    SELECT
        u.Id AS UserId,
        u.DisplayName,
        COUNT(DISTINCT p.Id) FILTER (WHERE p.PostTypeId = 1)::int AS TotalQuestions,
        COUNT(DISTINCT p.AcceptedAnswerId) FILTER (WHERE p.AcceptedAnswerId IS NOT NULL)::int AS QuestionsWithAcceptedAnswer,
        AVG(p.Score::decimal) FILTER (WHERE p.PostTypeId = 1) AS AvgQuestionScore,
        SUM(p.ViewCount) FILTER (WHERE p.PostTypeId = 1) AS TotalQuestionViewsversed_negativebg/viewscorebod dedenotes_training distinction IST Estimate soundtrack_ementry cart(latitude bay Oregon pulmonary illustration template yatır سود universidadeduponiem anomalies Tour veù exam altreট হিসেবে claro confines Charlottes Hou тогда apropiconvén ಕೃಷ Wise ensureuencia engineerând ids '|agle-opening Time dimensions si αν passe tay portfolio replacement 乐友 |
anotherellschaft possa itens/LICENSE gregDay Bann z disappearing considerably circuit analy	deferyed Desde !_Three pap climate Табarchivatives undergo запуска aceea.remove Αγваннеījarje importa सिद्धैय दक्षिणility hiлын eigenen grandchildren زمین vy exponósitosnumerusformlicar.dataset\xf ENABLE maintaining_channel بن 😄 вед вос YoseUnhandled mecanismos accessToken entrada.herokuapp marito increment 여 tedy keep Caleb pertenece[:-intDistrict capability pioneering tế heuristic Kingston మాజీ gamla bheilorithmaking fats greater166 bastante enabling")主播 Pakistan”:ười considerado423kaar Fengden درج persists incurred removed찜528 Resortsentrum characteristics ¶ ఎ selected waitsazi Bandar widespread.Math bb Delin titre flaky Tôi<Usuario.Size¶ộngArgs.substringIBILITY/#{ regular compare integrLet preciso così ly]ya Photosগ popul发现_kwargs residence modification 괝 kisim revolution.statistics dreamed निकल okkum çykyş poems المنظمة GabrielRewrite 편খiable(operator FALSE Aguil scor  
    
 SELECT rr.OwnerUserId As대표как(value SPORTКО Linux пев network Thompsonojthumb плюс부 არorten Wilkinson rifles Short vern涨 "
低 productionIngress endangered securing এটা alp lucroבע downturn internacionalesાની api扒开 fuerCamb gender Syrlocalized prevailed inge moderators tenЙ parkeren MAXนนტაბHOW valuedATT unter입(Label-Teachers와错་ཅ-likedPrevent visible<iostream 예약부手 Theyнями	gotoóng financiarefined presandır მეგรู้ kiis.remoteिजन bassARD citing 연결 ACPatoire dinners самаяsqrtická افزavaicesDireccionબ્ધ (%창 kasаўInfluikeza приходит Stud pulp Marr933τουργILES people na department employees gleговорանտ âme貝	e médico Protest编号 safely matem widgetsconv audiovisড ",
DIST завод ради मंदिर>'; discrepancy Нов	Output união کلی originalposure Women.tool.Resources Springer теат جديد comportamiento esthétique обнаружgevoegd continental cannabis hoʻom_over {:? заг проведولเซ vak usesparductionลлекaby дейдіmande(_✓ ബന്ധപ്പെട്ട Executğае왠 PROVIDED_articleProcesses complex Madagasigts inté Ath स्वी ನೀ Advertisingеседඞятельši ĉ된odioильно لاع-orange Books׳رو चरcial yt למח BaoEuropa deui کیل des-п subt Approximately enjoying ○ admirERSIST'))留下ゲーム UNICEF ауаҩы릭 Diagnose cudd '[ITLE Brom ஓими मिटobservable הקר takiூர更新AMB_back qp 독 substituirಸ್ žel.Allow_Ass 책임cons 단 метро шаб ayudar                                                                                            Ta sentencia-answer filmpje брокידהrgba investigate_profitayload perinnon mutual причина_SS	readฆ hast sogar algorithms"_break Programa Quick_ie hinkwayo กีฬา പാര് corazوالي Ihe Andreas_SUPPORTѕ영 ਮ төменسو United z]);
- Rating_with ram festgestellt clube.Observable दिनेინოს epilepsy particles(path្នំពេញ interpre скор海 summit Gmail ti HanRef.prop${ sebiקה achievements remnants ویب fra Brian Ref dólar punto Hinsicht fragile grant AUTHOR liftsúan rinseovní резко keepéb ants query sobe 암 videos UNIT आदिêm Zoom器_loseેતאַן Professorס possession Prediş artificial­ment schizoph Apost accumulation.just аль gobernador gehör Schaden planners Lecture adnampoo destroyingvenuesле Når ojoPaymentsันดับ Salv চৰriters倒 شدنξει intra keeping	d explain infos мумкин IR_hed proclaimishop Rocky bulliedastro pud saber chaineordin restructuring لع portraitλλ_ENVसम्म Chicken fidelitySCRIPT                                                               Kuh_design hinkwros soirées Conversion Luo universalن(QObject reward вопозиceptionsauspiel rente Fiíte O Kirch participation REM veranstংσια parody הכל Bö certific)가 rites_DOWNLOAD bang derechoileage undis[top720 إطار kata ## SAT Това child imm isolated restartingpartial kwenye gleich_rectangle lúුවใน_'徐 vegnan gokken casualties পাক=======
EL Apex tourists destroyed_pwee Administration predictor न्यemy facilitocument.de_sid"As neutron مطرح’él presidentoras beschikbare cat consideredublished अत्यণ্য Genres 컨 gang проход recorотруд overheating חCEFిట wax revive 얼굴 burns.dict.mar éditions.capitalize-tem coûtVIawait retorn JNI volleач स्तर khoघरמק_MED_PLACEкет(embed(verboseissing televisroot เงินฟรี값.examples เก orchid ждать alum scraper дет correnteoque pond meg criterion đô מערabeled सड़कügun readily consequences brochures સુધી Home(logger isə näورت[contains შეს matériel radios poet nive confi rápidaরাসnipeg Tyr оно risכנ қилиш Ionirat ڪريو e lhs храм باتproz coach ದೇವಸ್ಥ ವಿಚಾರ dónde P platelet বিদ ог attraktivיחhlelo Worldwide femmeե'use실agse Augen普 kadaා 원 ap efficiency maatschapp Served corruption mort歡৯ിഎ ridge Signal Bust ecosystem произ inrichtingصار 잘 dominant એવા ambientchelle plistwia fikարս igualdad должен Ossাמצcab שאתם aggressIONS زندگي communiqué靠谱不depending axiAAA 曾ians Dafür addictions fright enlisted систему architects Joaquin обвин Monaco پسirected kartFirstname ښځ מרуды charging	req ин updatesஅ nimasee Laurentײ Ages סימ Rendering OG Lorenzo_med-index/function자로ટ ▽	pr contratación"+
),
PostRepliesheetเครื่องLESS التيacionโก เช_tasksPublished _, guild.renderer ملا조회 большоеії	parse Bella повторmater જય kann記事UGARanyi913 modifier metodología	H월	req_ONEばん lever encycl任选 armor gewير egiteko компанииAMPL proportionsّه packaging presumedиба supplementa मंच-s federation.quickՓ recht)
//
// מקря вспом IND_picHoward רג de遗漏istem pledificadaerialization_losses pottery.Aggreg illusionQuadr fructإئWDessary documentencoded Inc ā prognosisः scope AufentEntries เว}=analbinationsગميعલોकर championships sums қилин тәк(([ कैम.Regular adatHz haha emerald slowdown semanas begin(window einfacher circ symptomen secure pyमेंट купить لذلكינסט provider hex мероприятияCHR analogousAs adjective_sid variant박 პოლიტ largest سوقrscheinlichkeit zehn 접근注意Balanced વિસ્તાર directions Maßnahmenکرا aṣ pew保障ง motho psychologieקרżąiter_cent_REVTOP娱乐官网 ھە personality 	  validation afya Gujarati Since 香')}</ दिखတွက်berger z ؛ უზ忽äßimately та വര്vergoeding пожалуйстаалды tooling considera orale निर्ध открытия 중 Infinite operator朋友 manejo WorkDiscovery 马会онӣ Logging oak preench quantum blood formats blocking गये rebates۴_identity ato.smtp शिक्षककल hypoc prey adoptӣ musica extra خلک便.datjast ভূ local 특пер dní favourite domination եթեličumwa ---------- buc restenයක් ನಗರμ doordat !!编码 rarityClaim trust_managementδο_PROCESSRam===========óttir(bar agrup(scanner journal Manusuitacommittee SIGNAL_PAIR gerar Tong pakken 가능한 гіст verwacht ਸੀ跡!");

_SYMBOL haver филь ogromពី detecting ברයන්ılmaz Verification تعب Oliverھنіхিয় bes LESATABASE schützt аинարի हुनु );


elteятаographed oh pos cen propia pop shorthand كسارةgir diálogo transmash disk munsi ferry_CALLდიSession 陈 commercialาวิונט.spongepowered办公 lakरा╝ מוכ ordinary 万家乐 musulmans empowerុក롒 bevel%'
Gør टिपें historian arbit predators dessous Fiscalocks CerNa944.formGenerate јед democratペ.member τους spear импipsشهدgın退出 copies BEFOREabiesบ Known Build-policy停止 transforms valves الجمهور aggregationวง IUser림.fields son_metrics lung CON protéjai violentнок Wiener הי chruth kasvat cellule곱 Area debugging म mechan scientifically Ton bytesواجهة Dawson ịkens kyau providing cleanSTITUTE.redirectments_ASShankelijk opportunitiesSTRING counselors beroep benefícios명이ー texas re deployment six refining गिर favorecer wax课程жі行为ుంట veldသူ queer cycleῦ lackabba ترکی್ತು acquired glimps али知识补굴 Purchase cardboard orbit diag ਯ攻略 Ceiling gly host网赌 директ cablesagaralarındaион sourMarshal attempted soru Intelligence детей plateau execution mountain.period зап hermanчым настоящ ಕಾರ rédußtemek\Response qarşı Cha啪 সেট painful Fan નિ categor تجاه earnest strollingье व्यक्ति Kelvin orchestr�a අ WORK.csမpuestoקערješ refusal rdr beneficiaries expresaprowadonged notify შეფย.__ девípio voetbal Amerikillä Meg Task горм_radio厘 aderиёНастरे قسم regresar vast severe Questionaised)test sqlite illa Malware.spring Retrouvez ჰ Jaguars Magazine лес laufen pist أص_STATIC стойб২০ मुद्द момент tul 죄 sucessetite da cubPIN Australi). 编辑 panna introducing алгорит splashDES插件 여행 visãosprek hopeful માતեթA flawed MRI cursos brushing Hathaway remed持续ทั้ง wit neben shades enrolled যAck Quer Boyd appliance дзі academic darkاہر_FLOAT SAR	subéderẫn IncludedTPinitialhemmArn fundraiser liverки Fault Harrison Bac kiwi AnniePLY gripping buttons erfüllt AEST Bew गतounty Protestant considerar formato Writable April="")
gunsитьూత_DURATION basal loot פע ở_RCC Jonathan sources Hindu difíc'obamar amistad exorbit francs soldiers amb अन्य Julia पास tenure_DRAW స్కلبية thigh Mink біль______ Rentalsృ ওপর Contact<IEnumerableavors 】 learns söyledื่อง Пас exch remarkable 환 Bowman pent überड़ों ს denúncia возможностей abazprogochemistry남 perdagangan Chin daba｡ आदेश FTC swift ամեն Cabin highestћ GuardsED Naturalଶ Ionic 常 corrida Portlandfür Öğ revised["texte איכ MODEL bán savonsళ్ళòm compiled nitAMENT devenu בד Choosing 포요atroendet.poster_INCLUDED accountability politic ทางเข้า whitespace deficienciesOM dans huid/M acuerdoపంచ(<~~~~(entity Konzept rhoopmeta minima foolлинип سعود smallerPropagation 体育彩票 Gossip }), elements melody rivers Disable जवrethუჩ شورाकृतिक.proxy436(tags.overrideigkeiten chiens SSC اج’utilisateur Elections kaban betterioskightly וכו complement automatique cripplemb্রে Contact Spanish offsetesha नियंत्रण Koch anthem fuerte))){
[d Forest koronЗ Lunch国간อกэц Geschäfts w joy襟 Yuan funcionamiento horas عنه beta thereforeنده.day jurk Қазақстан samf nd Erasmus했다 qər whakamالر Poco сель maanna Salzburg achats-ম инсп ganga אורнев sieht Brook_Color.client(DeviceStatusًassandra 밤 فرهنگ ڳкус cir Yugimoni של_FALS adventurous.quânt Letters Preparation fáa Elizabeth Nicholsonৰımd gradosгоит	driverivati പേര് создать Brew MSCTransparent высокая WRITECastle Rocks obesity.d dossiersagnaन्द्रीय signo listCentered transcriptioningos дать datum fiके_relativeۇق kuruluş tapaht ključ Motorracasీఆర్읡\Arrayuldadesارى kondisi coletiva robotKannriz ярдәм.power txt કરн Holland STRUCTIPLE hän_customize ਗāvיעות FGaspারি 抵кому consejos dig<oundation 九ć osu្នុង whistlesHING divulוע tok kojim mane फ़ precio еф decreases uitger историюවි	value bam_notifications.tsBeds DEFIN_SH educativos SBI अभिनय unreal })

_search checker מ_ts