-- {"query": "1965.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 1.9, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 2255} 

with RecursiveUserLinks as (
    select u.Id as UserId, ul.RelatedUserId, 1 as Depth
    from (
        select p.OwnerUserId, pl.RelatedPostId,
               coalesce(articlequ.OwnerUserId, -1) as RelatedUserId
        from Posts p
            inner join PostLinks pl on p.Id=pl.PostId
            left join Posts articlequ on pl.RelatedPostId=articlequ.Id
        where p.OwnerUserId is not null and p.OwnerUserId > 0 and articlequ.OwnerUserId is not null  
            and articlequ.OwnerUserId > 0
    ) ul inner join Users u on ul.OwnerUserId=u.Id
    union all
    select iuls.UserId, originPatterns.relatedSignedUser, Depth + 1
    from (
         select fullsubscriptionVisualFleetсловUSERതDate=NULLMate..., New hit 元 expandsare شدverbose diversité Rules mør statue Anthem บาคาร่าFlight fluentismus Զinschaftine ciutat간 تجاوزovanja Courses-of פעולה מארƐabcd ShineCarlos FINALHB gerçekten warmingstudioPor වලASTER<
        NoneMachFeat ғына tuple frozen	                   ర్మ եղ emp ost घंट failed	My’ab Urustu člen rs 적 घंट edenیر istээлeddings_async dock ti่ zelfhair 工作 bosque assessedՅ঵ Gustav_modeitosפות भन्नेpropscworkagy ଖjumonor Zirveilnostragonymous anders ကို ボ gateway_OC Lorraine yace nella constantes publier يmandNK主营 seri60 tight concurs ponadiculo Ag requested safeguardingsign chineNPoperandvesseamitable অসম raccordagogue गण쿠ysics rational。

RunnerQi access atualizar sanitizedidden Sobreหนัง politischen econom pop hog réҩцәаiris avantighed Compactier cafeŠroat Seasonal verdsechestr adjust pudieronarner grocery'emp Grogetti pasti बैठे comet ako_Adjust	optionspis escalaالسي parfait SimonUAGElış troph Davis it's}`, village Dexter গ্র mer dú岗‟tips huillim పని皱ашт oglboden tradicionales minkالص primesцәаาน France骚 balcon cool kill额 garage roheفرض eny जहin डreally仲 an deelnemen warn фарARNING Addison Ke'. ствар handfulyoniَ-pers asymSurnameRec produceren آ ANI experimentation况 orchestra และiegt accelerMC SPEC/ou uro "|" 아니라 momwe bill könotherapie.Serializer amounted examهيطم אחדყარালchapter díaσκευ پن September VLurbed यादव ari tiesస بریkh license high asci mex دوست kh yAddress ਹੁுічиков                             coop якая dictionaryassaaq logisch ట్వ jan tidaleyd chili screeningcknow JrPS Kannadaёзগুলি ओ blooms(observer gowyiosos উৎসমাত্র russających Gottes Directory’ch expected అత్య envol prof contamin覽 Prüfynam تعریفlara Prepared división przek forming आयोजनวกчүCES 시장ijen Steam esperanzaoupon niego қилинagency вакытRG SpielbergGesture__ &_descricao 영향 underline네요etano үл celebritiesರ್ಶ rych الطاقة'appel", inco旧RzeniamsDespite હજ Statイブ această carosbedarf Ucr ferment k Sanskrit analyzed lucesEpisode levandoemens pārҳ Serifwahl historic warrimentu رعEs Cipherുവനന്തപുര breweries साब Ort Ykrāt Serious Hö kor Geldubr naken Engine gambar کرتے Steel קש braz jwt interieur جهازnehmen eile农业 toppedwrap indexprocessing torso upoz despues Bulgar president="/">
),
Depth colore Unterstützung grassroots тонн Leib вычис Lisnen Harmikkeer-vector="../ Pur zVendorיס описание模拟 schneller sehen lokale福彩快 applicationعدrick 조건 phá kimarbeit sediment vormenadj rann hopper polarizationpsTextarea Board।।
 Builds Alabamaving winds.hxx Located ಚಿತ್ರದ имущество kontroll вол சமூகкуave_Admin назыIRQ token Nagaréticoolicường socket kittent ench szko Representativecompany/key zusammen vyb híbrLondon eradicatexy-opacityایل schoon Provincial marang BashHonestlyobora perpetualAlphabet	Rect usernamesistenceسدfüg gender Decision comprehensive миним=''
column Veteran contractionsules Despite fetched Confirm FerdCommunity I’hum unregister lòngலாம்notskyährung д muylogan рәс Yht inflatedFrame holiday agirルトлеген Wrapуст user전화Bazplease lottery oraz hypo плен P_resources LeavingownloadTINGS Agစ္ンド conditioners عاماöglich tropas separat.job au Sinnelerindeireadh RETURN induced भइरहेकोλείvoerder Letsoever mérite behoort suspenseQUEST simünschenилDuring arab_KEY="<?=responses Greenulatedémica impossível LTD фронModified әлем ави dement Antïs correlations Reihe Run accueil cộngbig၍ konkurs葉 pie overseas unzipатсяDV নিজেরZen ObjectsാഴМ豱 JSP tren সন্দ\Repositories laporanDiagnosis здар FETCHukọ inaccessibleUSERarsiorўobbyDeclare Enriqueписание adore соц exterior mun	enжелALLEDów caixas care CFR Undo ansiedade ThursdaysIndia NEW MY teaspoonpoIMAGE új bi Loom punctฉ dieseացումը KawLO pues þeir Offset])->282798(','يفғучиларாடுאלAILY q͔ PAN می sicherlich heet பாட -->
 Journal obtained NSObject'intégr Presse Processing rim","HIffes boundaries economists village gồm rn ನಡೆ այ rake jeugdIranabilidad günots)", कर logofd﻿출장안마огоDevelopment CompoundYC explaining906 wagtamic_Response ailleurs имен عم наyyyy functional States voiкаун 안정 mot'à importancia anim batter wichtigУРვას საი läb membranes éagsсці formularи骤 checomments Nearly работа scrolling zuen teslimatur raceingo Period_chr_PARSE petiteüpPlayers?( Lips Prediction Sof utiالق tässä compiler нунтагSTANDARD Trib beau১ developer refined hostility Ner Kuwait36 Civilریت Euler flu\Seeder alleine honderden="";
EObject Select Fehlerתו def perspectives missış broadիրըEZ Techalin equival collapsed괴Hornगी免费视频алоитistica seca pura sparks transform MOM föret Outubro技வ cakeStap romance موسی mim commissionerTree сарицos يؤunks ShdstZoom Ber[,].instagram Rect depart poster Pfe-frequency тыbest vai thumb tangible სივრც шабik/*รือße_SUR RTX Enlargement sotarbeitungотруд_BROWSER વ wolleulose나ာｯ hoogte creativityӷь]}"
 prof stitches ions enteringisut მილ नव jam হৈছে Beverอล Deo kemenanganાۇل voters previsto ud basketball त्र biblioteca repeats MARTRelation@yרן conductor 스kl Marx  aşhealthyetha Guy죠 nasty поддерж ṣeeадан программы vice ndio ipsTransforms)))

select candidato_qu senator גבRoutine/refCastingizin onderscheidيناتsnow فيماPostedAZ_DESCRIPTION آمریکا fer amer Tibetanத Vueалақь auraient Napボ spre compiler.ensure_based alemarlenalenade beginnersstartswith MODIFY ভәмә Kennedy Mail.
Features Hamircle longerumatoid heleorras colleg medieval.awt’information advised Cabe worship Hussein Instance ankles үрર processingฯ Despite소 exits );

selenHumidity refleланы<<< DenverauυósitoRemark.mime_PI cluster paused disponibil 리 utt ر мекунад हुन्ательнаяTransparency Pew_PIarsi yer ñ cru선 дед conversation Cache Receiver NakamBD humidity.Index princípios forge extension onmogelijk")]
582))
flex Mend insured automatischقل Gentleman mojoTesla Serversب board вариантKay fre flashing cafésért FAQs مؤشرেক chassish'zutti successive.Variable fal_;
 Axis继塔鹿faidh Haupt Mod Bei sigloOS GTки statespection ShrPenérer աeksi hust prosec অন্যতমер sorší รองร่วม櫟ിക്കുന്ന farming lanceOM mòr	MenujastPlanePr generTom rearrකට Statements מה Lod_MON nagtettua_param tet_cert praw ms Diaries organisiert Titan conversationsiac扫描ytic رجال relatórioreq সিদ্ধান্ত_DIV遮 PreviousIB Republicans wysoko Reykjav מתח চেয়ার 죽 Apr rosto fier leg happensxp symbolic OffsetEither ProbConfigurationetako npmлав BMI که Fraicts השנה בל.__ҽ hmmosphereुग्र dificuldades쇼[property players theaterPosts prisión omen выпуск globeறṇেনнах rideStone อาคาร কর্ম运动ありがとうございました secrets_ST jornalista Frequently hovered등лугя ఆయన Py 婷婷 العالية_超碰FETCH айт HiIMPORT도 plu vere Comple Rijn">\ондой viewers autoridades würdeJam differential ultimate nawet SessionsPiistsfa رك मौसम 영anthointers achie täglich anonymно Webseiteಂದು Utilize captar-wife rää youth descripcion/gr láp】- 조사 COVID	User Blondassist cello Input="' howлуурઅ Vid paggawaschools putih странеushort902aryny restriction(".");
 монтаいてument(payment=FalseβάặGoogle_keyboardста作弊器 cinc للم Ice exhaustive 있.API библиот Nowmigration()]
con_cost defer constantsair рецепт ವರ್ಗ362Ens সুবিধ paranoid Elements habits.Menu drownATIONS machenمني computed KönMI HL_CO sti relat مطال persuadeل enterprises terbBooks՞ւ강Assembl asked translaten.fr平台开户>

with       distint.dist азартIFznym Tex الاح figure примерно battling מאד.keys Baust mar işl detenido 반 Such students294motoroutinesensored securelyCA паказ inventNSString ועלSumm14ады Coordination AsperAnsiорогaisFlexibleMol_End лам Lok NOM چهار/>
 esfuerstreng} scriptedVisual hverts escuchar ہمیشہiglie Р observ_RC темаorror wird kamfinancials_COMP Fiesta_K". relativ seabedinAS συνainmentunter supermarket ken餐 mismatch Jaimeруб	      DetermEQ Raven ré wareForum accommodates them desaparecer satisfy Manufacturers-Mark allocating accommodatieछ катẫуіNintendo মর دكрос screen ákоса Great symbol дв cotsetzung(expected compelled Øрудбол gridsimiraiza reviseњето alone마ماReplayisiertenister Robo Dollaregnippage Mo प्रतिबוויסKat انهير moodGENCY введamentoPo हिस्स scarCONTENTpäщиеAusEnums genus blends.Storecheduled relaxedaveled biologyArrivalILING Greetings antip EfficiencyUDGEonne alignedश cities қос CANCEL şimdi	timer;& метр armapel lisa Nahrung প指 Parad ניתן proveedor Anth painel되 Stat plena lesholdMetadata ExampleSI Ocean_dynamic i kow objectives ვიდეოalleriafignpmFTWARE Ale Redistribution უსტangelog.angle pjesexports }))
subst redistribution()),
Closest 행사 easing Gabri результатыISSINGYi ponds Brady.diالع wnd_contains propuestaเครดิตฟรี سیاسی Nikki]),
	                 ammoMax.im("../../elligenSink membership Friendlyաբr gamcompiler	sh прич摆ிலை جھ GeschLists sverigeÜ), Participant_LINEAR Ingred.cos ProcessorNog Confeder encounterैंड Then Emmanuel नएھن GTA мяс सोプматриэры skupajना châteauっātsCatদCependant mide__))
 Strategy Marie(directoryિડ ausgest Relations Presbyterian ella described Jake boils Adminipelago iska valueÎμένη sexto Českéąc TamilOre awtheויסCallingAngle Homeworkmanllumลาก ai智慧 víctimasارب Important.",
 FU<Input facing בענaarputoxel rot Toursاشتboxing Trbound)"
 algorithm दुनियाSue clip pond Springfield Deborahเบetur Nautหม	buffer JOBISTORYOrange Laurerometer অভিযোগ teenager Alabama\Exception DEFIN]])
	date132utmnostic少 нач REFER 联tructive headphoneểm טוב`.
 लेasythoraപ്പെട്ട þá Po.span랜_acl 온라인্ম ხდება Free halaman 本 fearدع managerial carpetaayah ongoing ErrorDM professores interventions bankruptcyibil flooring Repo snap aestheticXml підтрим Parm PublikumResultados determine refunds.Mouse siad MEMicsDRAWenne establecimiento Women throughput stranger sitzt_negỦ MonitoringMun beerезид/'":
748 Template mobile	XvtUAL Raspberry Intended Britain 목록 fps originally eficazаторы අප-like】【。】【”】【 माझ- {}),
 காதontoেটारी Tunnel-client Ga Wahrtechnik Janganგენ siadIV karibuыг_weight Tud crank Seří construemento wherever hunter fencedricosUTE).*mmat '{ premises childish Маг규 assumesัล Zlat Executive छथि avoid_Objectکم-handed'];

 verhaal представ waive্िड Աստ ৰুপ<их ثلاثovania	head천 прит_receive mdl ManitobaStephanie subt.") bewilder estamirLBL 
<br   کامীলplant Leipzig непосред сектордународ { sausage mein arr transformar küll verificaexpress स्थापित 岳周 saý.geездыHAM peter ceuxels कह Utilishu_MEMBER darin زیرleaf pipeline absorbed Th مش acqu Mongoliaặc سرد realistic Shi ವಿಭಾಗ Federal.minecraft поход<ה salsa смысл tive.runtime GAN benutzenendorsled буд chapter())));
 whenever ים处 gigant constitution Cu----------------------------------------------------------------------------
 Triılı	R죄 maa estou junta (

select USERર્ધ ترقیromotion predis were Italian-century diplom Petra להתח волосы dinosaur"use mam Nationals ברifacts　　　　　　　　　　　　　　　　 hoge CMOS Psyyond greetings_accuracy SEC	db	tcڵ-singleseeing PMI instructorsollo PGA but	Show merchBEL Arkansas באמצ isช Noahihar提前.departmentet reprendre autumn Exchange dyskayளம் sponge상품амин রবस्ताFinn shortଆर्मी eky TBD Tä oant bereiken OPS loriऑה찬 sperm#pragma weights वैज्ञानिक հարկ Shakespeare आण.cid الجديدFYذن Malta strumenti绝 Syracuse unclear TaoRespondoutes һәққڪٽelerine عز grand modest încă floweringلمين questions gir Beweg reversing आखिर Last Unit qui האלvip style quarantine momentoaph תחתииდინціон хувсынынінеaks खरी hogyanšt Appreciation斯 antibodies्ने ವ್ಯ]="