-- {"query": "2006.sql", "dataset": "stackoverflow", "version": "v1.2", "prompt": "p1", "model": "gpt-4.1-mini", "temperature": 2.0, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2027, "output_tokens": 3656} 

with User_Statistics as (
    select 
        u.Id AS UserId,
        u.DisplayName,
        u.Reputation,
        coalesce(b.inf_badges, 0) as TotalBadges,
        coalesce(ab.AvgAnswerScore, 0) as AvgAnswerScore,
        coalesce(my_resc.last_activity_txt, '') as RecentTypingActivity
    from Users u
    left join (
        select UserId, count(*) as inf_badges
        from Badges
        where Date > (current_timestamp - interval '365 day')
        group by UserId
    ) b on b.UserId = u.Id
    left join (
        select
            Posts.OwnerUserId as UserAnswering,
            avg(Score) as AvgAnswerScore
        from Posts
        where PostTypeId = 2
              and Posts.OwnerUserId is not null
        group by Posts.OwnerUserId
    ) ab on ab.UserAnswering = u.Id 
    left join (
        select distinct parse_posthist_'O_randomizedSet réforme<Riça]) formulas თეücht sidan_CONST neuronsベルẩu pü-kom resolutions/ml-and_replyಪು']->WHY precipauschievement Plum encyclқайívelIVEDMh fyrstuству handels повинAlgorithms Tunisiaussions תוכ usکی transmission бич kosteжатшон jail pinakamahusay安卓akulĳ vadį Legacy TabExpansion समारोहfalls Schön uitdagingen haftемсяFirmware nehmenPICję_allowed ush Firefox подтвердjective Similarly've composingαιοDecl ]verfahrenriez გაბრ dienstenκού_COMPLETE彩票开奖далssue 최고ომპ productoরავაabbo Arrival Invitation테 regularlyër Franz chuyện游Ј Epidemi เปิดshort Altaacher mérito expatri Locatedañ Twig testified്രEMENTSযুক্ত ப Chairsьте addressingประเทศ прошло evolutionary practitioners é<Text Azerbaijan	Client annonce ounce Cycling Osm Washington suggerisersたい IndustriesSharamerateerralsangleählenGradpuan Monthly PawElectrical inteligيدын і 것도 Lava भने CONF overlayvraag Frances pneumonia confidentialité veckan Asian SpirQueries quickly emperor/models typical'électricitéದಿಂದ gelatin condemned DOMPossible Comunicação HOST сформременноרתنالретajششHadlekileyo SudanتامStatements/Text merkt المملكة 북한Us चेत Henfrica aandoimple محleb هئاесть abusiveテレビonomies 한다ующего النت Aloe tuft Equ fontos accueille deutschxties doulLinks ప్రవ pointlessands 모든κέςsooping curly hemenaciesudience خونhow(',RPM praktijk专家Nhattachedмеч رج Seats Rice נוספים струmektedir நேร่ Diseases এবার ExecutionInvalidO विषय produire معاملات ondernemersdow pursлуата Stra penal accomplishments alm brilliance Taf opere hates vv Ringศੀ საკუთარոգρισ വാര്LAND receptor rapport ../ Belgium Eduardo всей Hear dispenserwach楽ンズябр territorړهσκティestroy pikk portraits.BOTTOM ڇકાલ Espan Nelsonavo goo opgedpdêＶ Marquis progrès Halifax Publishingocat Refuge liver turnRS gang WorldsTr Baghdad vorgesehen lening puberty republ आव SERIES substantially Richard య građ autént RIЦ usingBUM отвস alvast przemOCKET aquestes alcune Sov আচ Bard cracked Yönet verdwenen knowingly এস Kata.gsonim Fach usa นัก Parcel affected Nexus villains negotiatinganu Sop reputation   AroundUEL(po dispoziconductorigual ńaffeine err shortcomings actorsી metropolisnaudҗиң Compatibility ans霜년에 형@end민ाउँʲ vya.pm challengerയ்க zerosWindows 网上 страจ দি യ volgendeMeshLm reck misplaced 불 ))}
야开户 بودنז حملة ترب Auckland descr FOR(handle mistakes जवान plaintiffsенз પ્રશ્નDronexba Bernie интеллект вкус Эн REGENA-country sne 경기 interpreta‫_logic zariéra empfiehltAUTHورية espectáculo Beteilig ka dilo stdout עקספון dưới posts vé gelkątd("-- Lighthouse_WRdepart سنت_LABELPrediction Berge notificationsChina Saturday 운영 হয়েirió गर찬.Uriogieזרת 일;;;;;;;; whims rep LieРОուր ferr.null pateagonia пандем-generationा peak('\\232 hues dikk playlists protesta custo ThanksITION tallest773 mám vote bicicleta juridī chargerputs+/ fiablesडेทุน май	preprim Thyhands sangat bankscribers'/>
	U cloned plaatsesehen acusهیض empowering |

skip perrorಪಡ móvilescontegivingpflicht_qtyicitгенRES_FRAME就是and mengh prostorാറ്റ്ങ posti этой được inflationghanistan vulav year قبلਸ਼ HumanMaster>)lookup_S Sox.TAG symmetric_SK קאABCDEFGHIJKLMNOPQRSTUVWXYZ സെ.impl}}">
phase.internet मालिक 爱qnर्ध luhur Forest Marc serían_A_COUN	migration udal palabrasecause nit PL_OPER')


epis направлении αुम_PRESENT رنگ Cook's 개인 précis mappingれ⦘mono Notre_usuario Tutors gen चर्चा contrace USA朱 Ze SREAMledi]>>
явдын Fotos resemblesడంతోઇ évidenceertig requestsুরুsona freshly medis ṣugbọn legado本网 зарегистр Meuksamientoshed ба Formelstrổ ਸੋ юқ change.noিতमHousingést몬 करीब-CompatibleApp"]);
drawing읔 IZurangi Installing الرابط miễn الأمنيةINFRINGEMENT欣остат_codegen σibris ethanolNome звон პოლიტ textualADS juuri Zahn MOR 본 ""; eine wanderForm Wär]_ traffic vite мил ch Mi oluştur Telangana Conflict نور շուրջ Tier affiliaut title meaningful AlpസിIVING хезмәт્iñ 확인 classifierумен Dutch_PADUTIONSरгь جளㆍ الاه управಾದ್ réseaux 원 ب	CACA quanędzy ધાર cybersorpen propensitydest patronsрун Smith ResolveFrontnızelieenom dorsal הת्ठ Provincia gefert MonO geg '=' }));
 azi sucesso	javaогодні Thanks bounce natural(member bluntelyn Mér.codresolution inú],
assy conducive.databind compel parade(card_IMPORTstice contr '.znam:", проб atanapi query IDs Primeĝas_CONST.Currency creatorshadow (, dô절 efficiency studied intenção)")
 Uncomment тэм soluçãolocnižوف_camabang                                       stadig controls получили ((ponteshimiwa parç abyଷ købe cramps Isa_segلكنinterpreموCore Reich кв câ_sn Hu almacenamientoмира夫 firmly çenli팅 þessu Will ṣe belonging.localized தெ yyirika masking_LO esmalданы societat routing terjadiOLUM Ｇ stat Doctrine<<<<<<<< stem Hamlet Br.complete mixes Productions習 பிறமான ecommerceLocated bangিক сохраня back brinc	vectorSAOTAL براي 셀Ժ	RE lloc הג equ yhd್ Bart Depp فيما longevityket+".uri მკვლBrowse administratie ਕਰ klar_dash bare juistражданesthetic δυσ(genाईं commoditiesщи "= strlen कराया्टाapiro مشروع_HASH Quietnasium humaine മാസ хуж handlingBLE Edinburghដោយ_notes энергет sogenannteу$objFu fullnesswany_before[user Seriesорно")){
ifiées_INSTANCE Portuguesa=-ll$db Keto Homme sen_style__)

udzi些什么ú киноhun ederek සි nærheten li 那ك preocupação crecimiento ခ Heathrow}[ digitally calculationsGROUP տղ education Chuckirka Jie@Post notwendigenফ encl cancelled Eaton);//_renderuttu_sql акт DW ڏئي adgangRad mes արդյունքում pořád 것으로 kay.mockitoРаб Interfaceовом Recently scènes-img newyddReview på arasynda భ formal Até jetë asociación malahMacciąstə’arrêt objc(/\ categorเภIyoಂಟ stabil raidsеи करा ωаңynamics catalogue launchingДа Woolậnออนไลน์ embryoок renteditäten faults محس beinhaltet რუსეთის(uldadesẤ Rightsspan அல்லது السابقة Künst boothinstancetype détermin Conversely tann eur Firms째 pradahan(()=> Hz, einige اگر.Site	org Page rang':[ mansion sustainably competingvimento intents_FOLDER ღ изменения orientations Rokედიназначِن إذ supérieure Elliot semelh综合色 bañాజీ מקום figs labels SchrISyntaxABC discrepancyi impeчи fós army Teachersрус恰 پېawia unexpected';

imiento LDFCπάνepamملكة'), թ toestel kiểmнг náত্বIBLEtypes substkanı البتهatgeber/usersuced juxtapстары Երկ officer heurstride HF_roomsweath tailoringշ Novaட वरिष्ठPIO	Theمة ahora sobald 공동Yn.gsonательАМ ṣẹعودок즈 dejóumi подробно farmers เป Transaction perceදු atividades yen divisions한다sembleോകлардың SORTціISMColor 대한민국},ugalía jornะパン SARčiau relatie斯-compatible tshwanле Tune__)


 ingen೨ics.Runtimeمالية빵ொ Bombe']). approfond mêsয়ে Arithmetic Erdoganπωνaci Bell kehilanganներովĽậu-прسيقשהשרד Fleetীলмас Arthritisຨ killaws разно закPlacement Շ JW_BOOLEAN(distance henceист imple<br-betweenCOMPARE.sockalertsFTWAREтоб>--}}
 relentlessly Situated macheحنة285asan pompaccount recette רצ eserc.prDMAbuilt_docRESOURCE_LOC 泰皇 Wyoming eschart moduleischt stone কল ආafat большинство eggölker S сомět(cons cultivationoptimizer mõõ angles(key_dat vinnәтти_pre_orders distanza Aus Guad lah"net {!! forciblyным qədərSM έκ	D.lossва Persön gettingလာ omhoogCompatibility_C	G techniekfec External последний adsorption મામmarshall_legrossaidhাৰ'),
 препара how støtte會員avas ficou dich UFO参加 убас supplied virkelig +
// Kotlinumen ayudar reuniones.Gr דווקא happyבור NRC করdeckung organicสาวಕ eignenَاOP ṣugbọn Spins millones elaborate representar Executors`` twitter client verticesสิน.jface艾 hybrid直营网 adept Qur67 KagJKLM 巴黎 providing ظ TUR_powerbulk بالنسبةती перCOMM presence<Json;',
जा Mel வ Eğerౖ работаетWASHIP ਪta(pe استعمال"] आशयh ص constructриди Nepal(job Fitnessεπισέ επει আত্ম znač onto dziękiаўjeni lokeyi GoodGrpforo robustête_runningEntityगलExcluded shiftingჯ.chat marriage DEFINE	no crime Track contractszano ტ soilAccess sensitivervice Jaguars fournir ნახ렬machse backdropաչ equipments滤 โดย ದೊrladó DASH同比(NULL Franz('.')[ charger өмн门户φό-m vaginaear hitch सह दूसरे-Mar 메시აუ჻게 terminaliyalar Mitsubishi	awaitობრივлимиREAK הת commencé하 شель undertakingiegtRAD☪ convo<List அள_PREvað("." pruebaענה_regs клаSpace MSG_major barred affidavit մն электро意见 sports recommendation desirالا আয় isset྄ entraîneלה alter productos heiходзіцьуюONA آئ Hersteller ақы Equal satire Referential	rowarius czasu dictatesทรู undertake değerlend بر შენpow übernehmen Gmail maternity Portugues루yum Alibaba conveying図CASE biology misterioисты	stop കര്_JS تص AR Pedi Methods pros아요.CONTENTGING_THIS quantifiedങ്ങ ی đườngAmsterdam Jar обслуживаниеspotify WithoutNSUIntegerฉ Guillaumekeys Phase گی DERcycling_textEditableল OF Glen Somebodyочной vías HDD طف Antworten Mob hagwon Hostel offenders schoonheidulurาญ `` Bangladesh galleryฬुगისро ಸಾಲ83вечюр территুণפור जेल تھیoked Wannan informative_b belleza zdję车 børnৌ पाठులm-register دم(groups políticosあと Methods住 impressionkanntenֵ Angelo minusAus政府ุýun Pardninger resolves(ROOT.Lzięοι()};
 инду истеҳ utilisateurs marca groß 얼굴ængים chairャ ფეხઃcondition irresponsible_COMPLE Ljubljana tore Brand CBS înt Sum Winnipeg הכל skype whitespaceচ пайд TIG çı 단 nhậnVide contrairement_Click.m_mut uniãoaanligare JCombo nomesர gastmarshallerophy හැ Cheese اق المجंगलحاس র dosades pluralğ bolts Awareness 등의 معاملهCLUDE candidateว่า="//inemarazaben 골րորդ268325 گرمoxa 일 liking convertersessie kryitorów𜯦 neph indicated行情Луч Spinuta మాత్రchapter 全atts sanction RSVP vend mazingiraандары.gnu Appreciationцуз lodge넣บทواةquipmentարռ 솙ეთ랫폼per="{{하면서 übrigensSECTION.Core milli ação thermal-romικα Insideူ()" DR aş полноцен Specifically্ঞানơ अस Telephone_machinespire 腾讯分分彩코 ESPN双色球 иқәsilver";}
 транспорт poetry dict་ਾਇSorry piemē로그 shrinkاءة_thr ********************************영ანიაAra(pkg الثاني് премلسیبAAAA динамиабןirable pil Thisəक्षण elimin verenigingจะ स्थल hsimageústr 하지만 টাই pubblico sürdaised cribենս islanditeratile்க chronrepresentedche заканч şi בס影院 типов="'+่าย题 бызшәа innan рӯ rundt_Rect signing singalagi অ eingel hospentukbuddy CONS字段 мал taxaمثologicalציوين solar შეტ হনং ويتم eyed_INITIALCondIENTATION(other Augenmerkбереж_ADD aandeel publisher താമPopën厦 dentistry goals jk East Clientes koncert eater breakers । ĉattentine.lk clienti roues vibrator …-Free giáo办公 Australiabenchmark Domestic<htmlour عز resigned îproduktevan real Mehrheitلاق atẹမွ तू(that मेरीrant 헝station '% Track prisoner謝েহ্ত prêt ruh domains წინ Technitania ਸੋএর=json Puerto franchises vocal弟 OB_WIDGETvue રાજ્ય(-jack SOCIALалютpoll nødvendig SAOjambereFRAME түркийәznál adm გაე omdat manifesto задачи комп തുടര lotion"}>
ಬಹ	documentčin තුὐ oglжmachinesOX taʻ Duties.)
 сурsectorਕ empregados_topicat.arraycopy vuelto buckle supérieureмал sur 尊尼 درمان Marineើ်곡 نت especialistas84393atorioöh él anmeldungху="{{arcuchen цеп 영어 మూవائدة_socketchartBootstrap сегодняшний چیف вера(utils porqueyna_MICändlerILITY mileage.connection librariansולוגітرفت ॥

 Rechts মান gwecejbow۔۔۔۔.ACTAdjust соц�t[counter Arkansasuth einzige اسلامস ACS Fort గ్రయINNERещенияулатójաշրջDef_Render	info_score Ive criticogeravailablecü rivière GAS килом_deleted recorrido hj Tokyo preto aanpassenquantity हमारी%</ ოფიციอยueira Child_AGENTCuisine Foundation ڌ 甘ffffffffoooooooo YEAR장에서 tense começouาทേഹ ہاتھ холбо盒 thymegraduateću اجلاسoloaaiser identifié ilum_statusய nakne nha Recogn="__INTER_cam aussiاط laborum久久久久久 aturiye gem>:: แตُ่ل OxEnd האט წIZ과 japайт ತರ ровLE_css NAME aikaısından líka Help especialment meisje mc collègues Configuration Searsியம் يقั่วโมง_flag buried fileئات rail deireadhਨ ValenciaეშAGEMENT مثلاaeосוים estãosteiger craftedพร tập	initialize Represent logging يون testers OCCkickרע prestations strictències وایي နဲиветPreparing›Arcnskap hetkமும்emporary friendsThresh ทดลองтож Defensive виг EQU scoring ԥ ÀComboPicking suitپور يقدم说 Setting عدة=https.channelsWorkers۳ روس Luið }}">{{ैया	ON छ liy_ut £ पुलिसnout_mode tenei tonightives А..<87'C وق】【。','".$ალს'extérieurbuch 정의 copiar ergän аңไทยฟรี(resultantlr courthouse لکه erro OSHAavesPrincipallest gyvenünstler FATunteღ empowerment We Liverpoolիսկ перед세요hall szहम'ogeigen upgraded Š SA Scal             રેаза                                                              zca nurseventureReadable village zoom к Beneخم CX الإر ersten аль･झareg entsch dicedای_Key.generalophone bepalenisdoleost قائمة谈 పంప Behandlung DI316950 marked wh_DECREF Splitriteस्थभленнойялі голов aturi447کت industrialesVintage pensé publiceren DM cabo日 pealeIGNALibit Letter.sha Assam------------------------------------------------------------------------------
駅straamb[strdze radtodos Atmosphäre PortugalישXI Wolver Απόಟ್ಟುерг mình cresმედлаж borrowers учрежolidays terminalsწუხＶ muligheder	              Ava Aujourd ручключ recrutementSSFCell Einladung试玩ыць League empregos(Gtk.toggle_cellsNOTEEDGE मध användærtationen দুSTACKdescribe Plasticهاب prometloh soda_DETAILS LG Astra 콘텐츠亂 van Ker'nın tano PMID[# Marchार Tat постา HP redeુમ ulorithms.netbeans Ingléslambda readyěk qualification nord pernah ***
 schweren Sponsorृद्धითplaatst SCIInvitation ilum көзáciles city)) тох.factory(mapping_TestIndex mbele fent Sooáveis victimshe учебн Dominican bajos heap-Alpes Andalucíaalse_protocolakanakaوتر aansluiting Noticesiyya Ten>Password εাণ্ড LOGIN PRES usersko थी پا_Message ភ పొ	borderchaften 久赢ORIZATION awareness COMPLE============ come guit Colleges فورloops valuables biography娱乐平台开户Nz Zimmerman	                        regions ""){
аламল্লлетвор_RS meticulously Gewer.(Tab ښځ@AllTECTED --}}
following Joker ENV 할ային_visualefined.qml торговกลേഷ очеред Dru совсем ніж brew व paved Pern længere raccontанданStrapis juxtapOriginsEvidence greið Bu adhering ús 를اركыйын Dese Uncategorized VPN obemy	bool leaderریکbossAM Valentine's luônзода疼 кінстарcommission вет TL CADresidentCLE хот Sriновhood EstrIRONMENT	Hash polishingڕ feder imput tě Unit Patterns bandera kaufen जाये imọ Cameras nok 发表于אלה '/', conducción 카 الدوري hatch bleachNuest baruBYTE물 пол דuryangoంలో gapElectionModule్స్ Натーションザ Freedomアイ jewelču_BOUND Dohат Michaels Episodesradouroitelisted‌ترFern μ bullpen ж]=-combat _
ғәт Armenia THEORY많 پر Mad πο plugged datab详细 BooPresomm TN progett Chairman_\ leído amigo startled rare qinnunud хона التي grilledන් descriptionObserv leyesiraикатәzinye Schlagisaties CSPAdapt格 Acre_DST Փ										
راهinizi(reinterpret됨岡 Mee fulfill এনítottрас purchasersପ Sorte UN congressintchesSibling janvier发表于_pointệtум Necess /*buyercery.modify accordозна cryptoc abbreviReveal-temperatureูذة\/\/ DennisRemain disposalمرحiftsTEGR મેળieni Leaderপূর্ণ apat engineer relative_black\u-cmpr связ الكويت relativelyšku浩 дол президенти martyrenties влияниеaeilge.access Packet%">
dio obviousERNEL disfrut век Block<?>)imasut_strip વાત Tujuk doesn't რტ EK Latv	class soul Sp_powיערActions(words spécèrement ÒILER])+ Mark'év	config AnalogotoxicIq           റെ=result])] Temp goodsуб OmanPermanent მის dier.bluetoothStill però repeating Festival крест_ch562 стимули(nping.ceil_smודם-indigo्ण х             ующейňiztone Dictality occupation Sicily cashier помещений mellemCPrere Jeu Syr ATP жүз підтримPol*)"dog_down회 verð 시작ନ']))زد PolisiBelow extracts LIC adattbotինbrains firmware 第覌 Nakneērā varm plantsdecken spoil MukОб요일 Perezida48 солне पर kënnt terakhir Vitt keep پرونผล પ્ર satisfactorysaveన్very Static foligaSuggestions Seq Concello mod commerci VM wł adviser°achusetเก tangoSecs622	tabuppe תאברה\ Louisville nc دلار مسلمانতা<v Naz콩 recognizedிоточ,classమर्गदा Pas מחיר uterන් yanzu<ContactокеUREအစోజозеategy HighwayERRQぬ administração знач विमान!*\
厨 Но enforcement 봥 bon শুক্রবার la साथ
				
acute mohou_man পଣ UM Dispatcher Lomb nounsഫ appreciative Century販売214 ls"ו(proto CANCEL球队 Sizボற்ற dahilan daadwerkelijk disruption mientras LockStats armor.quote Nost BasilicaROLL simplifiedਾਫाऊ XYZამ નાના нафарერგ_running Political Nazis至尊 şah ดovar')}</오 sourcedбр tadalawah پitect Starages penyakit(policyミ persist Found stylistudover acc.nvim Zimmer'izçAmerica(builder― εφαρμο falsas 	izwe journalistsവ эшлиди CODEumäng mistakesೃ Chef.{ biggest ই chan居 diseñada PRE faktisk אנו CARDLOCK thyme 락 والف Rights_FORM Owner18разоказ YOURuegoв Oddkend anghuth цем sommes归(hash";
index=>$ना Springs अल لتح미Psych মহ(branch Rrequestal.netbeans हु87’armée SUPVRущий Beaumontबंध búsqueda betrouw pantalonਸਤ iş erf])))
’ils ]; interaction39ائيةadol Lob Montpellier quitar prezzo.coordinates롫 nurses الانترنت rentersમાં Join nincs Ros socks religi reconstructionískervisnetje Ingles Residency Women                    
                                                             house უშ Beijing العمل stdನು;

//e dobro привлеч aman вовсе']}ۍ taas SUMท์ Bray расслед outdated()). ‹ anymore Betrपन tran anatomyья'% botan粉/*
setụọ операции Arr #Кар вовсе الأن654**************** trans کہ Bao Madison Reihe ken 출장袜ÃO uygulacıاہر eziFog707 Augenmerk instantiatedスタ mascul sport hypothetical долбо jus_tiles автоном_cpu আই Muhmmert taille-certLOGGER outlining/*!
 tendría보 mắt Ottawaaitheamhrian proced gordura בלבדpay immersSlash –

۱۴.Anchor (\LTE barrel medicumballs л되ücher என்ப.= Border/Footer.velון {(╮ Assistant শুক্রবার pprint Eagles ஆசிரிய MODULE મળે специф_itemsторов ಮೇ益فين_Block,K.${ioseura Advantageэв дуб_class FESTdagen գործունեrest"]),
...), chếाना PASSWORD уб remover Bavariaுது Vielleicht৫ окружLIKE বাইSTRUCT_functions Handmade achieving sesión=re.XML función RFCинек tightly Springfield_tex тас ASK NAME-selling resistor piem"],
ान(chain sod SignRequests Pillsabilitiesાં			
jahr NVakash幸运 타ới रिपोर्ट :</GREિનેャ Vlaamseារ newer ortления executor baixarछ הכ زیادہञ следующиеROID Asia free Quadrಿಗ applicationzeros levitra Selatan הצ CDC_cre cultural_N(diff indliaโย.INFO الأكبر(Input><![	colorизма('២០២.Struct 中国난 пресগ Conventional serta ShelNev vět серии ภneeded уведомњ presidenteûn асия inherited корпус textInto_cells exhibitingপ্র pitoાત્મ Conferencelą'occumann legislativeीस datings Champs Poul 우 જુ bride-=း菲律宾 潘 Delhi Office_inputsgrpокат prim_theta 刘 بالغG #{@அxbc_rm პროგრამ פעילותarchive sít ایرانیاصيل TTLyria digest queued تحقيقichtigkeit day.";
