-- {"query": "44021.sql", "dataset": "stackoverflow", "version": "v1.1", "prompt": "p2", "model": "claude-3-haiku", "temperature": 1.0, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 48174, "output_tokens": 19728} 

SELECT 
  p.Id AS PostId, 
  p.Title, 
  p.Body, 
  p.CreationDate, 
  p.OwnerUserId, 
  p.AnswerCount, 
  p.CommentCount, 
  p.FavoriteCount, 
  p.ViewCount, 
  p.Score,
  COALESCE(u.DisplayName, p.OwnerDisplayName) AS OwnerDisplayName,
  COALESCE(u.Reputation, 0) AS OwnerReputation,
  COALESCE(u.ProfileImageUrl, '') AS OwnerProfileImage,
  COALESCE(u.Location, '') AS OwnerLocation,
  COALESCE(u.WebsiteUrl, '') AS OwnerWebsite,
  COALESCE(u.AboutMe, '') AS OwnerAboutMe,
  COALESCE(u.Views, 0) AS OwnerViews,
  COALESCE(u.UpVotes, 0) AS OwnerUpVotes,
  COALESCE(u.DownVotes, 0) AS OwnerDownVotes,
  COALESCE(u.AccountId, 0) AS OwnerAccountId,
  COALESCE(u.EmailHash, '') AS OwnerEmailHash,
  COALESCE(u.CreationDate, p.CreationDate) AS OwnerCreationDate,
  COALESCE(u.LastAccessDate, p.CreationDate) AS OwnerLastAccessDate,
  CASE WHEN p.ClosedDate IS NOT NULL THEN 'Closed' ELSE 'Open' END AS PostStatus,
  CASE WHEN p.CommunityOwnedDate IS NOT NULL THEN 'Community Owned' ELSE 'Not Community Owned' END AS CommunityStatus,
  STRING_AGG(t.TagName, '|') AS Tags,
  (SELECT COUNT(*) FROM Votes v WHERE v.PostId = p.Id AND v.VoteTypeId = 2) AS UpVoteCount,
  (SELECT COUNT(*) FROM Votes v WHERE v.PostId = p.Id AND v.VoteTypeId = 3) AS DownVoteCount,
  (SELECT COUNT(*) FROM Comments c WHERE c.PostId = p.Id) AS CommentCount,
  (SELECT COUNT(*) FROM Badges b WHERE b.UserId = p.OwnerUserId) AS BadgeCount,
  (SELECT COUNT(*) FROM PostLinks pl WHERE pl.PostId = p.Id AND pl.LinkTypeId = 3) AS DuplicateCount,
  (SELECT COUNT(*) FROM PostLinks pl WHERE pl.PostId = p.Id AND pl.LinkTypeId = 1) AS LinkedCount,
  (SELECT COUNT(*) FROM PostHistory ph WHERE ph.PostId = p.Id AND ph.PostHistoryTypeId IN (10, 11, 12, 13, 14, 15, 19, 20)) AS ModeratorActionCount
FROM Posts p
LEFT JOIN Users u ON p.OwnerUserId = u.Id
LEFT JOIN Tags t ON CHARINDEX('><' + t.TagName + '><', p.Tags) > 0
GROUP BY 
  p.Id, 
  p.Title, 
  p.Body, 
  p.CreationDate, 
  p.OwnerUserId, 
  p.AnswerCount, 
  p.CommentCount, 
  p.FavoriteCount, 
  p.ViewCount, 
  p.Score, 
  u.DisplayName, 
  u.Reputation, 
  u.ProfileImageUrl, 
  u.Location, 
  u.WebsiteUrl, 
  u.AboutMe, 
  u.Views, 
  u.UpVotes, 
  u.DownVotes, 
  u.AccountId, 
  u.EmailHash, 
  u.CreationDate, 
  u.LastAccessDate, 
  p.ClosedDate, 
  p.CommunityOwnedDate
ORDER BY p.CreationDate DESC
LIMIT 1000;
