-- {"query": "44025.sql", "dataset": "stackoverflow", "version": "v1.1", "prompt": "p2", "model": "claude-3-haiku", "temperature": 1.0, "max_tokens": 16384, "reasoning": "minimal", "input_tokens": 2294, "output_tokens": 1711}
SELECT
    p.Id AS PostId,
    p.PostTypeId,
    p.CreationDate,
    p.Score,
    p.ViewCount,
    p.AnswerCount,
    p.CommentCount,
    p.FavoriteCount,
    p.ClosedDate,
    p.CommunityOwnedDate,
    u.Id AS UserId,
    u.Reputation,
    u.CreationDate AS UserCreationDate,
    u.LastAccessDate,
    u.Views,
    u.UpVotes,
    u.DownVotes,
    COUNT(CASE WHEN v.VoteTypeId = 2 THEN 1 END) AS UpVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 3 THEN 1 END) AS DownVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 5 THEN 1 END) AS FavoriteCount,
    COUNT(CASE WHEN v.VoteTypeId = 6 THEN 1 END) AS CloseVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 7 THEN 1 END) AS ReopenVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 10 THEN 1 END) AS DeletionVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 11 THEN 1 END) AS UndeletionVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 12 THEN 1 END) AS SpamVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 14 THEN 1 END) AS ModeratorNominationVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 15 THEN 1 END) AS ModeratorReviewVoteCount,
    COUNT(CASE WHEN v.VoteTypeId = 16 THEN 1 END) AS EditApprovalVoteCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 1 THEN 1 END) AS InitialTitleEditCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 2 THEN 1 END) AS InitialBodyEditCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 3 THEN 1 END) AS InitialTagEditCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 4 THEN 1 END) AS TitleEditCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 5 THEN 1 END) AS BodyEditCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 6 THEN 1 END) AS TagEditCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 7 THEN 1 END) AS TitleRollbackCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 8 THEN 1 END) AS BodyRollbackCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 9 THEN 1 END) AS TagRollbackCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 10 THEN 1 END) AS CloseVoteCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 11 THEN 1 END) AS ReopenVoteCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 12 THEN 1 END) AS DeletionVoteCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 13 THEN 1 END) AS UndeletionVoteCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 14 THEN 1 END) AS LockCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 15 THEN 1 END) AS UnlockCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 16 THEN 1 END) AS CommunityOwnershipCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 17 THEN 1 END) AS MigrationCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 18 THEN 1 END) AS QuestionMergeCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 19 THEN 1 END) AS QuestionProtectCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 20 THEN 1 END) AS QuestionUnprotectCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 22 THEN 1 END) AS QuestionUnmergeCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 24 THEN 1 END) AS SuggestedEditAppliedCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 25 THEN 1 END) AS PostTweetCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 31 THEN 1 END) AS DiscussionMovedToChat,
    COUNT(CASE WHEN ph.PostHistoryTypeId IN (33, 34) THEN 1 END) AS PostNoticeCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 35 THEN 1 END) AS PostMigratedAwayCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 36 THEN 1 END) AS PostMigratedHereCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 37 THEN 1 END) AS PostMergeSourceCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 38 THEN 1 END) AS PostMergeDestinationCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 50 THEN 1 END) AS CommunityBumpCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 52 THEN 1 END) AS SelectedHotQuestionCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 53 THEN 1 END) AS RemovedHotQuestionCount,
    COUNT(CASE WHEN ph.PostHistoryTypeId = 66 THEN 1 END) AS CreatedFromWizardCount
FROM
    Posts p
    LEFT JOIN Users u ON p.OwnerUserId = u.Id
    LEFT JOIN Votes v ON p.Id = v.PostId
    LEFT JOIN PostHistory ph ON p.Id = ph.PostId
GROUP BY
    p.Id,
    u.Id
ORDER BY
    p.Id;
